#+SETUPFILE: ~/.emacs.d/org-template/level-0.org
#+TITLE:Slegetank's Blog
#+HTML_HEAD: <style type="text/css">.title{display:none;}</style>

* [[file:blog/20200114-singyoung.org][歌唱我动荡的青春]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20200114-singyoung.html
  :PUBDATE:  <2020-01-14 15:55>
  :END:
<2020-01-14 15:55> | Other


苏联时期的歌总是能把青年对于国家、对于未来的情怀唱的如此激昂

[[file:blog/20200114-singyoung.org][Read More...]]
-----
* [[file:blog/20200111-winning.org][赢 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20200111-winning.html
  :PUBDATE:  <2020-01-11 17:18>
  :END:
<2020-01-11 17:18> | Book


Life is not easy for any of us. We must work, and above all we must believe in ourselves. We must believe that each one of us is able to do some thing well. And that we must work until we succeed.

[[file:blog/20200111-winning.org][Read More...]]
-----
* [[file:blog/20191003-liutao.org][《六韬》 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20191003-liutao.html
  :PUBDATE:  <2019-10-03 22:05>
  :END:
<2019-10-03 22:05> | Book


是故人君从事于富。不富无以为仁，不施无以合亲。

[[file:blog/20191003-liutao.org][Read More...]]
-----
* [[file:blog/20190926-baozoujunguo.org][暴走军国 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190926-baozoujunguo.html
  :PUBDATE:  <2019-09-26 13:21>
  :END:
<2019-09-26 13:21> | Book


不知我等是狂是愚，唯知一路奔驰。

[[file:blog/20190926-baozoujunguo.org][Read More...]]
-----
* [[file:blog/20190908-TheManWhoChangedChina.org][他改变了中国 － 江泽民传 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190908-TheManWhoChangedChina.html
  :PUBDATE:  <2019-09-08 14:21>
  :END:
<2019-09-08 14:21> | Book


我为长者续一秒

[[file:blog/20190908-TheManWhoChangedChina.org][Read More...]]
-----
* [[file:blog/20190825-rime.org][Rime输入法同步]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190825-rime.html
  :PUBDATE:  <2019-08-25 15:43>
  :END:
<2019-08-25 15:43> | Tools


更香了

[[file:blog/20190825-rime.org][Read More...]]
-----
* [[file:blog/20190623-sanguozhiyi.org][三国志异 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190623-sanguozhiyi.html
  :PUBDATE:  <2019-06-23 12:48>
  :END:
<2019-06-23 12:48> | Book


后世眼中，前三国所以比后三国传奇，不在于后三国人才凋零：实际上，后三国极多问文武全文武全才的人物，但大多都太聪明。

[[file:blog/20190623-sanguozhiyi.org][Read More...]]
-----
* [[file:blog/20190522-crosswall.org][科学上网]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190522-crosswall.html
  :PUBDATE:  <2019-05-22 10:49>
  :END:
<2019-05-22 10:49> | Tools


翻墙

[[file:blog/20190522-crosswall.org][Read More...]]
-----
* [[file:blog/20190512-GunsGermsSteel.org][枪炮、病菌与钢铁 － 人类社会的命运 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190512-GunsGermsSteel.html
  :PUBDATE:  <2019-05-12 17:19>
  :END:
<2019-05-12 17:19> | Book


各大陆民族长期历史之间的显著差异，不是源自这些民族本身的天生差异，而是源自他们环境的差异。

[[file:blog/20190512-GunsGermsSteel.org][Read More...]]
-----
* [[file:blog/20190509-iotroad.org][物联网应用路线图]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190509-iotroad.html
  :PUBDATE:  <2019-05-09 09:13>
  :END:
<2019-05-09 09:13> | Book


软件的关键不在于编写代码，而在于将软件所能够实现的状态以服务的形式提供给用户，并且以此来引领社会的发展。

[[file:blog/20190509-iotroad.org][Read More...]]
-----
* [[file:blog/20190421-emacsprofile.org][如何定位emacs卡顿的问题]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190421-emacsprofile.html
  :PUBDATE:  <2019-04-21 15:39>
  :END:
<2019-04-21 15:39> | Emacs


[[file:blog/20190421-emacsprofile.org][Read More...]]
-----
* [[file:blog/20190331-emacschinese.org][emacs内置中文输入法]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190331-emacschinese.html
  :PUBDATE:  <2019-03-31 18:46>
  :END:
<2019-03-31 18:46> | Emacs


真香

[[file:blog/20190331-emacschinese.org][Read More...]]
-----
* [[file:blog/20190331-daduhe.org][非常突破 1935年大渡河之役详考]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190331-daduhe.html
  :PUBDATE:  <2019-03-31 16:51>
  :END:
<2019-03-31 16:51> | Book


昼夜兼程二百四 猛打穷追夺泸定

[[file:blog/20190331-daduhe.org][Read More...]]
-----
* [[file:blog/20190317-from0to1.org][从0到1 开启商业与未来的秘密 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190317-from0to1.html
  :PUBDATE:  <2019-03-17 15:57>
  :END:
<2019-03-17 15:57> | Book


事实上，资本主义和竞争的概念恰恰相反。资本主义基于资本的累积，而如果处于完全竞争之下，利润就会消失。

[[file:blog/20190317-from0to1.org][Read More...]]
-----
* [[file:blog/20190101-thegrandchessboard.org][大棋局 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20190101-thegrandchessboard.html
  :PUBDATE:  <2019-01-01 13:22>
  :END:
<2019-01-01 13:22> | Book


简而言之，美国作为世界上首要的大国确实面对着一个并不很宽的历史性机会之窗。

[[file:blog/20190101-thegrandchessboard.org][Read More...]]
-----
* [[file:blog/20181226-PowerandProsperity.org][权力与繁荣 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181226-PowerandProsperity.html
  :PUBDATE:  <2018-12-26 12:28>
  :END:
<2018-12-26 12:28> | Book


如果无政府社会被一种适当的和平秩序所取代，那么产量就会大幅度增加。

[[file:blog/20181226-PowerandProsperity.org][Read More...]]
-----
* [[file:blog/20181216-emacsA.org][附录A]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacsA.html
  :PUBDATE:  <2018-12-16 20:13>
  :END:
<2018-12-16 20:13> | Emacs


[[file:blog/20181216-emacsA.org][Read More...]]
-----
* [[file:blog/20181216-emacs8.org][工作流分享]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs8.html
  :PUBDATE:  <2018-12-16 20:12>
  :END:
<2018-12-16 20:12> | Emacs


分享一下工作流。

[[file:blog/20181216-emacs8.org][Read More...]]
-----
* [[file:blog/20181216-emacs7.org][搜索与替换]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs7.html
  :PUBDATE:  <2018-12-16 20:10>
  :END:
<2018-12-16 20:10> | Emacs


在工程中搜索、替换是程序员的必要技能。

[[file:blog/20181216-emacs7.org][Read More...]]
-----
* [[file:blog/20181216-emacs6.org][文件访问]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs6.html
  :PUBDATE:  <2018-12-16 20:09>
  :END:
<2018-12-16 20:09> | Emacs


Emacs的强大特性之一就是对于文件的查找、操作、管理。

[[file:blog/20181216-emacs6.org][Read More...]]
-----
* [[file:blog/20181216-emacs5.org][基础包]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs5.html
  :PUBDATE:  <2018-12-16 20:07>
  :END:
<2018-12-16 20:07> | Emacs


有些包是基础包，它们会极大的改变emacs默认的操作方式。

[[file:blog/20181216-emacs5.org][Read More...]]
-----
* [[file:blog/20181216-emacs4.org][开始]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs4.html
  :PUBDATE:  <2018-12-16 20:06>
  :END:
<2018-12-16 20:06> | Emacs


配置代码组织以及一些常用的配置。

[[file:blog/20181216-emacs4.org][Read More...]]
-----
* [[file:blog/20181216-emacs3.org][Mode]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs3.html
  :PUBDATE:  <2018-12-16 20:05>
  :END:
<2018-12-16 20:05> | Emacs


描述emacs编辑行为的核心概念mode。

[[file:blog/20181216-emacs3.org][Read More...]]
-----
* [[file:blog/20181216-emacs2.org][elisp]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs2.html
  :PUBDATE:  <2018-12-16 20:04>
  :END:
<2018-12-16 20:04> | Emacs


简单介绍一下elisp。

[[file:blog/20181216-emacs2.org][Read More...]]
-----
* [[file:blog/20181216-emacs1.org][基础]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs1.html
  :PUBDATE:  <2018-12-16 20:03>
  :END:
<2018-12-16 20:03> | Emacs


Emacs的一些最基本的概念。

[[file:blog/20181216-emacs1.org][Read More...]]
-----
* [[file:blog/20181216-emacs0.org][前言]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181216-emacs0.html
  :PUBDATE:  <2018-12-16 20:02>
  :END:
<2018-12-16 20:02> | Emacs


前言

[[file:blog/20181216-emacs0.org][Read More...]]
-----
* [[file:blog/20181117-americanclass.org][格调 - 社会等级与生活品味 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181117-americanclass.html
  :PUBDATE:  <2018-11-17 12:55>
  :END:
<2018-11-17 12:55> | Book


事实是，正因为这是一个民主国家，等级差别比任何其他地方都更加生机勃勃。

[[file:blog/20181117-americanclass.org][Read More...]]
-----
* [[file:blog/20181101-coffee.org][你不懂咖啡 总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181101-coffee.html
  :PUBDATE:  <2018-11-01 13:25>
  :END:
<2018-11-01 13:25> | Book


喝了这么多咖啡，还是觉得家里20块钱一斤的大叶子茶好喝。

[[file:blog/20181101-coffee.org][Read More...]]
-----
* [[file:blog/20181020-wine.org][你不懂葡萄酒 总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181020-wine.html
  :PUBDATE:  <2018-10-20 15:25>
  :END:
<2018-10-20 15:25> | Book


[[file:blog/20181020-wine.org][Read More...]]
-----
* [[file:blog/20181007-1587.org][万历十五年 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20181007-1587.html
  :PUBDATE:  <2018-10-07 18:34>
  :END:
<2018-10-07 18:34> | Book


我大明亡了

[[file:blog/20181007-1587.org][Read More...]]
-----
* [[file:blog/20180915-zhihuiqizhu.org][智慧七柱 从麦加到大马士革]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180915-zhihuiqizhu.html
  :PUBDATE:  <2018-09-15 18:30>
  :END:
<2018-09-15 18:30> | Book


All men dream: but not equally. Those who dream by night in the dusty recesses of their minds wake in the day to find that it was vanity: but the dreamers of the day are dangerous men, for they may act their dreams with open eyes, to make it possible. This I did.

[[file:blog/20180915-zhihuiqizhu.org][Read More...]]
-----
* [[file:blog/20180825-historyandgeography.org][历史的地理枢纽 总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180825-historyandgeography.html
  :PUBDATE:  <2018-08-25 18:58>
  :END:
<2018-08-25 18:58> | Book


谁统治东欧，谁就能主宰中心地带；
谁统治心脏地带，谁就能主宰世界岛；
谁统治世界岛，谁就能主宰全世界。

[[file:blog/20180825-historyandgeography.org][Read More...]]
-----
* [[file:blog/20180819-shangjunshu.org][商君书 - 百代都行秦政法]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180819-shangjunshu.html
  :PUBDATE:  <2018-08-19 09:56>
  :END:
<2018-08-19 09:56> | Book


勿以恶小而为之，勿以善小而不为。惟贤惟德，能服于人。汝父德薄，勿效之。可读《汉书》、《礼记》，闲暇历观诸子及《六韬》、《商君书》益人意智。

[[file:blog/20180819-shangjunshu.org][Read More...]]
-----
* [[file:blog/20180622-zenyangdanghaoyigeshizhang.org][读林彪《怎样当好一个师长》]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180622-zenyangdanghaoyigeshizhang.html
  :PUBDATE:  <2018-06-22 13:16>
  :END:
<2018-06-22 13:16> | Book


林彪当连长的时候，是全团战斗力最强的连；当营长的营，是全团最过硬的营；当团长的团，是红四军的头等主力团。最后东野从东北一直打到海南岛，51年接着打抗美援朝，即使不是林彪指挥，依然出了万岁军这种绝对主力；从此篇文章可以看出一二。

[[file:blog/20180622-zenyangdanghaoyigeshizhang.org][Read More...]]
-----
* [[file:blog/20180517-chinaarise.org][伟大的中国工业革命 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180517-chinaarise.html
  :PUBDATE:  <2018-05-17 20:31>
  :END:
<2018-05-17 20:31> | Book


需求决定供给

[[file:blog/20180517-chinaarise.org][Read More...]]
-----
* [[file:blog/20180507-lincoln.org][林肯传 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180507-lincoln.html
  :PUBDATE:  <2018-05-07 19:27>
  :END:
<2018-05-07 19:27> | Book


法律宗教
统一国家
解放黑奴

[[file:blog/20180507-lincoln.org][Read More...]]
-----
* [[file:blog/20180422-imageprocess.org][图像处理小记录]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180422-imageprocess.html
  :PUBDATE:  <2018-04-22 18:33>
  :END:
<2018-04-22 18:33> | Tools


日常的小图像处理记录。

[[file:blog/20180422-imageprocess.org][Read More...]]
-----
* [[file:blog/20180304-shapeoftime.org][时间的形状 读后感]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180304-shapeoftime.html
  :PUBDATE:  <2018-03-04 11:20>
  :END:
<2018-03-04 11:20> | Book


相对论科普

[[file:blog/20180304-shapeoftime.org][Read More...]]
-----
* [[file:blog/20180304-firstbattleofnewchina.org][开国第一战 读后感]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180304-firstbattleofnewchina.html
  :PUBDATE:  <2018-03-04 15:08>
  :END:
<2018-03-04 15:08> | Book


一条大河波浪宽

[[file:blog/20180304-firstbattleofnewchina.org][Read More...]]
-----
* [[file:blog/20180210-rhythumFromTheUniverse.org][星空的琴弦 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180210-rhythumFromTheUniverse.html
  :PUBDATE:  <2018-02-10 13:33>
  :END:
<2018-02-10 13:33> | Book


天文学八卦

[[file:blog/20180210-rhythumFromTheUniverse.org][Read More...]]
-----
* [[file:blog/20180113-booklist.org][书单]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180113-booklist.html
  :PUBDATE:  <2018-01-13 14:20>
  :END:
<2018-01-13 14:20> | Book


不定期维护自己的书单

[[file:blog/20180113-booklist.org][Read More...]]
-----
* [[file:blog/20180103-sqpiensABriefHistoryofHumankind.org][《人类简史 从动物到上帝》读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20180103-sqpiensABriefHistoryofHumankind.html
  :PUBDATE:  <2018-01-03 13:00>
  :END:
<2018-01-03 13:00> | Book


Sapiens - A Brief History of Humankind
读后总结

[[file:blog/20180103-sqpiensABriefHistoryofHumankind.org][Read More...]]
-----
* [[file:blog/20171119-iterm.org][高效使用iTerm]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20171119-iterm.html
  :PUBDATE:  <2017-11-19 18:58>
  :END:
<2017-11-19 18:58> | Helper


程序员的三大件基本上就是浏览器（Browser）、编辑器（Editor）和终端（Terminal）。每个程序员都需要一个好用的终端工具才能事半功倍。
iTerm + zsh + oh-my-zsh，很好很强大。

[[file:blog/20171119-iterm.org][Read More...]]
-----
* [[file:blog/20170826-emacsChart.org][Emacs图表优雅的解决方案]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170826-emacsChart.html
  :PUBDATE:  <2017-08-26 10:56>
  :END:
<2017-08-26 10:56> | Emacs


程序员工作中经常需要画图表，例如流程图、类图等。而作为生产力工具的Emacs自然也提供了(或者说不甘寂寞的程序员为其提供了)相应的解决方案。
这里介绍一种artist mode + ditaa的方案，相当优雅而高效。
方案来自于这里： [[https://www.youtube.com/watch?v=cIuX87Xo8Fc][Poor Man's UML / Emacs Artist Mode and Ditaa Demo]] 大光头讲的比我好，这里只是整理一下安装流程。

[[file:blog/20170826-emacsChart.org][Read More...]]
-----
* [[file:blog/20170529-SICP_lec2.org][SICP笔记 - 2 高阶过程]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170529-SICP_lec2.html
  :PUBDATE:  <2017-05-29 15:20>
  :END:
<2017-05-29 15:20> | Software Engineering


video:
http://v.youku.com/v_show/id_XNzAzNjI1NjU2.html
http://v.youku.com/v_show/id_XNzAzNjg4Mjk2.html

[[file:blog/20170529-SICP_lec2.org][Read More...]]
-----
* [[file:blog/20170514-SICP_lec1.org][SICP笔记 - 1 概述]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170514-SICP_lec1.html
  :PUBDATE:  <2017-05-14 01:12>
  :END:
<2017-05-14 01:12> | Software Engineering


video:
http://v.youku.com/v_show/id_XNTEzMDAyMTU2.html
http://v.youku.com/v_show/id_XNTMxODY1NTg4.html

[[file:blog/20170514-SICP_lec1.org][Read More...]]
-----
* [[file:blog/20170328-mu4e.org][Mail with Emacs]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170328-mu4e.html
  :PUBDATE:  <2017-03-28 17:52>
  :END:
<2017-03-28 17:52> | Emacs


Mail With Emacs

[[file:blog/20170328-mu4e.org][Read More...]]
-----
* [[file:blog/20170318-tramp.org][TRAMP学习记录]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170318-tramp.html
  :PUBDATE:  <2017-03-18 16:57>
  :END:
<2017-03-18 16:57> | Emacs


TRAMP是emacs远程编辑的神器，在此记录，以便以后查阅。

[[file:blog/20170318-tramp.org][Read More...]]
-----
* [[file:blog/20170206-magit.org][Magit - MagicGitTool for Emacs]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170206-magit.html
  :PUBDATE:  <2017-02-06 16:01>
  :END:
<2017-02-06 16:01> | Emacs


作为emacs里git代码管理的杀手级插件，其强大毋庸置疑。

[[file:blog/20170206-magit.org][Read More...]]
-----
* [[file:blog/20170108-blogWithEmacs.org][Blog With Emacs]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170108-blogWithEmacs.html
  :PUBDATE:  <2017-01-08 15:16>
  :END:
<2017-01-08 15:16> | Emacs


本文讨论如何优雅的用emacs写博客。

[[file:blog/20170108-blogWithEmacs.org][Read More...]]
-----
* [[file:blog/20170106-dired.org][如何优雅的使用Dired]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20170106-dired.html
  :PUBDATE:  <2017-03-23 14:50>
  :END:
<2017-03-23 14:50> | Emacs


Dired作为emacs的目录管理工具，必学。

[[file:blog/20170106-dired.org][Read More...]]
-----
* [[file:blog/20161120-AmericaPoliticalCutlture.org][权力是靠不住的 - 美国政治文化探析 读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20161120-AmericaPoliticalCutlture.html
  :PUBDATE:  <2016-11-20 17:05>
  :END:
<2016-11-20 17:05> | Book

迁移。
[[file:blog/20161120-AmericaPoliticalCutlture.org][Read More...]]
-----
* [[file:blog/20161112-chinafoundworld.org][从海图中所读到的历史--《1421年中国发现世界》读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20161112-chinafoundworld.html
  :PUBDATE:  <2016-11-12 16:05>
  :END:
<2016-11-12 16:05> | Book


迁移。

[[file:blog/20161112-chinafoundworld.org][Read More...]]
-----
* [[file:blog/20160925-emacstips.org][翻译：Lisp Style Tips for the Beginner - Heinrich Taube]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20160925-emacstips.html
  :PUBDATE:  <2016-09-25 12:19>
  :END:
<2016-09-25 12:19> | Emacs


迁移。翻译。

[[file:blog/20160925-emacstips.org][Read More...]]
-----
* [[file:blog/20160825-iOSSign.org][iOS代码签名理解]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20160825-iOSSign.html
  :PUBDATE:  <2016-08-25 21:38>
  :END:
<2016-08-25 21:38> | IOS


迁移。尝试用openssl解释苹果的签名行为。

[[file:blog/20160825-iOSSign.org][Read More...]]
-----
* [[file:blog/20160815-UPnPInspector.org][Mac下安装UPnP Inspector]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20160815-UPnPInspector.html
  :PUBDATE:  <2016-08-15 16:12>
  :END:
<2016-08-15 16:12> | Helper


迁移。

[[file:blog/20160815-UPnPInspector.org][Read More...]]
-----
* [[file:blog/20160721-block.org][Objective-C Block]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20160721-block.html
  :PUBDATE:  <2016-07-21 14:52>
  :END:
<2016-07-21 14:52> | IOS


迁移。

[[file:blog/20160721-block.org][Read More...]]
-----
* [[file:blog/20160716-WutheringHeights.org][输了你，赢了世界又如何 -- 呼啸山庄读后感]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20160716-WutheringHeights.html
  :PUBDATE:  <2016-07-16 17:32>
  :END:
<2016-07-16 17:32> | Book


迁移。

[[file:blog/20160716-WutheringHeights.org][Read More...]]
-----
* [[file:blog/20160312-CrimeandPunishment.org][当已无路可走 - 罪与罚读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20160312-CrimeandPunishment.html
  :PUBDATE:  <2016-03-12 15:15>
  :END:
<2016-03-12 15:15> | Book


迁移。

[[file:blog/20160312-CrimeandPunishment.org][Read More...]]
-----
* [[file:blog/20160216-Shakespeare.org][反映人生，揭示善恶 - 莎士比亚四大悲剧读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20160216-Shakespeare.html
  :PUBDATE:  <2016-02-16 14:00>
  :END:
<2016-02-16 14:00> | Book


迁移。

[[file:blog/20160216-Shakespeare.org][Read More...]]
-----
* [[file:blog/20151225-environment.org][工作环境配置记录]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20151225-environment.html
  :PUBDATE:  <2015-12-25 10:49>
  :END:
<2015-12-25 10:49> | Helper


2016-09-03 16:00:04 更新：

将部分配置做成了脚本，happy hacking: [[https://github.com/slegetank/WorkHelper]]

[[file:blog/20151225-environment.org][Read More...]]
-----
* [[file:blog/20151122-AdventuresOfHuckleberryFinn.org][我就下地狱吧 -- 哈克贝利费恩历险记读后总结]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20151122-AdventuresOfHuckleberryFinn.html
  :PUBDATE:  <2015-11-22 01:07>
  :END:
<2015-11-22 01:07> | Book


迁移。

[[file:blog/20151122-AdventuresOfHuckleberryFinn.org][Read More...]]
-----
* [[file:blog/20130705-selfview.org][立场决定观点 --关于政治历史事件的个人立场]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20130705-selfview.html
  :PUBDATE:  <2013-07-05 08:43>
  :END:
<2013-07-05 08:43> | History & Politics


迁移。这是我对于文史哲的基本世界观，简单的说就是“屁股决定脑袋”。

[[file:blog/20130705-selfview.org][Read More...]]
-----
* [[file:blog/20130420-unittest.org][iOS开发之单元测试]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20130420-unittest.html
  :PUBDATE:  <2013-04-20 18:21>
  :END:
<2013-04-20 18:21> | IOS


迁移。惭愧，这个一直没能实践。

[[file:blog/20130420-unittest.org][Read More...]]
-----
* [[file:blog/20130407-staticLibrary.org][iOS开发之静态链接库]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20130407-staticLibrary.html
  :PUBDATE:  <2013-04-07 19:23>
  :END:
<2013-04-07 19:23> | IOS

迁移
[[file:blog/20130407-staticLibrary.org][Read More...]]
-----
* [[file:blog/20130403-Agile.org][开发人员修养--敏捷]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20130403-Agile.html
  :PUBDATE:  <2013-04-03 16:56>
  :END:
<2013-04-03 16:56> | Software Engineering


迁移。敏捷追求高效，手段反而是其次，重要的是思想。

[[file:blog/20130403-Agile.org][Read More...]]
-----
* [[file:blog/20130401-MVC.org][iOS开发基础之MVC模式]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20130401-MVC.html
  :PUBDATE:  <2013-04-01 17:31>
  :END:
<2013-04-01 17:31> | IOS


迁移。App程序员的必备知识。

[[file:blog/20130401-MVC.org][Read More...]]
-----
* [[file:blog/20130305-bundle.org][iOS插件化开发之bundle]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20130305-bundle.html
  :PUBDATE:  <2013-03-05 11:32>
  :END:
<2013-03-05 11:32> | IOS

博客迁移。
[[file:blog/20130305-bundle.org][Read More...]]
-----
* [[file:blog/20130304-plugin.org][iOS插件化开发概述]]
  :PROPERTIES:
  :RSS_PERMALINK: blog/20130304-plugin.html
  :PUBDATE:  <2013-03-04 15:44>
  :END:
<2013-03-04 15:44> | IOS

博客迁移。
Bundle的应用，虽然这玩意到现在还是没有什么实用价值。
[[file:blog/20130304-plugin.org][Read More...]]
