#+TITLE: 商君书 - 百代都行秦政法
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2018-08-19 09:56>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

勿以恶小而为之，勿以善小而不为。惟贤惟德，能服于人。汝父德薄，勿效之。可读《汉书》、《礼记》，闲暇历观诸子及《六韬》、《商君书》益人意智。

#+END_COMMENT

* 摘录
** 更法
公孙鞅曰：“臣闻之：‘疑行无成，疑事无功。‘君亟定变法之虑，殆无顾天下之议之也。且夫有高人之行者，固见负于世；有独知之虑者，必见骜于民。语曰：’愚者暗于成事，知者见于未萌。民不可与虑始，而可与乐成。郭偃之法曰：‘论至德者不和于俗，成大功者不谋于众。’法者所以爱民也，礼者所以便事也。是以圣人苟可以强国，不法其故；苟可以利民，不循其礼。”

三代不同礼而王，五霸不同法而霸。

前世不同教，何古之法？...各当时而立法，因事而制礼。...臣故曰：治世不一道，便国不必法古。

穷巷多怪，曲学多辩

*** 小结
这篇很精彩，总起全书，想都摘下来。针对于传统势力的阻挠，商鞅对秦孝公说出了变法的合理性，大概翻译一下主干（最好看原文，很精彩）：
孝公说，“我变法恐怕天下议论我啊（当时的主流应该是复三代，而这毫无疑问是儒的主场。而儒的那一套看起来好看，用起来没有力量）。”商鞅说：“真理往往掌握在少数人手中，只要能够强国利民，不用理他们。”
甘龙说，“圣人、智者不变法也能使国家强盛，改变秦的传统习俗会被天下人非议的啊。君上三思。”商鞅说：“三代不同礼而王，五霸不同法而霸。智慧的人制法，而愚人遵守成法。这是个愚人，不足以与他讨论变法。”
杜挚说，“利不百，不变法，法古无过。君上三思。”商鞅说：“前世的政教本来就各不相同，何古之法？这些明君都是按照当时的国情制定出合乎自身发展的法制而已。所以说，治世不一道，便国不必法古。君上不要再疑虑了。”
孝公说，“我听说‘穷巷多怪，曲学多辩’，愚昧的人所嘲笑的，正是智者所悲哀的；狂妄的人所开心的，正是贤者所担忧的。我不会再因为世人的议论所疑惑了”，于是开始了变法。

变法的合理性是什么呢？三代、五霸这些强盛一时的国家都有自己独特的法制，他们都是当时的智者根据国家自己的需要自己指定的法令；而秦为弱国，因此因循守旧是不可取的，需要因地制宜的根据自己的需要制定出对应的法律才能变强。
“穷巷多怪，曲学多辩”用太祖的话说就是“庙小妖风大，池浅王八多”，异曲同工。

** 垦令
无宿治，则邪官不及为私利于民。而百官之情不相稽，则农有余日。

无以外权爵任与官，则民不贵学问，又不贱农。民不贵学，则愚；愚，则无外交；无外交别则国安不殆。

休居不听，则气不淫。行作不顾，则意必壹。

废逆旅

*** 小结
促进农业生产。具体有哪些制度呢？
重农抑商，百姓只能通过种地获得政府奖励；对不事生产的人按人头收税，减少所谓食客的数量；禁止粮食私自买卖，限制商人获利；禁止雇佣行为，最大程度的解放农业生产力。
废除旅馆
国家统一管理土地
对奢侈浪费的享乐行为克重税
连坐
不准随便搬家
不准到处宣讲奇闻轶事
官吏考核准则统一
加重各地关税，抑制商业
商人按照人头服徭役，使他们比务农还苦，这样商人就会减少，而百姓由于没有商人贩卖的奢侈品也就不需要额外花销，这样百姓就会富裕

商业对个人有利，然而对处于战争状态的国家不利；高谈阔论的文人也是如此，于强国无益。欲强军必农战。因此利用国家强制力使百姓去商从农，囤积粮食。虽然有钱人的欲望被抑制，然而对于最大多数底层百姓以及国家机器来讲，有力无害。

** 农战
凡人主之所以劝民者，官爵也；国之所以兴者，农战也。

故豪杰皆可变业，务学《诗》、《书》，随从外权，上可以得显，下可以求官爵；要靡事商贾，为技艺，皆以避农战。

官法明，故不任知虑

今为国者多无要。朝廷之言治也，纷纷焉务相易也。是以其君惛于说，其官乱于言，其民惰而不农。故其境内之民，皆化而好辩、乐学，事商贾，为技艺，避农战。

圣人知治国之要，故令民归心于农。...夫民之亲上死制也，以其旦暮从事于农。夫民之不可用也，见言谈游士事君之可以尊身也、商贾之可以富家也、技艺之足以口也。民见此三者之便且利也，则必避农。避农，则民轻其居。轻其居，则必不为上守战也。

故惟明君知好言之不可以强兵辟土也，惟圣人之治国作壹、抟之于农而已矣。

*** 小结
在群敌环伺的战国，国家如何才能强盛呢？农战，即种地、军事。如果国家不重农战而重用文人、商人、演员，那么百姓就会去从事这三种能更轻松获得名利的职业而不去从事更劳苦的农业、战争，这样这个国家就无法最大效率的获得军事上的能力。

所以只要法令严明，就不需要选用什么智虑之才，百姓都从事农战，国家自然就强大了。

** 去强
主贵多变，国贵少变。

国强而不战，毒输于内，礼乐虱官生，必削；国遂战，毒输于敌，国无礼乐虱官，必强。

重罚轻赏，则上爱民，民死上；重赏轻罚，则上不爱民，民不死上。

怯民使以刑，必勇；勇民使以赏，则死。

治国能令贫者富、富者贫，则国多力，多力者王。王者刑九赏一，强国刑七赏三，削国刑五赏五。

能生不能杀，曰自攻之国，必削；能生能杀，曰攻敌之国，必强。

十里断者，国弱；九里断者，国强。以日治者王，以夜治者强，以宿治者削。

以刑去刑，国治，以刑致刑，国乱，故曰：行刑重轻，刑去事成，国强；重重而轻轻，刑至事生，国削。

*** 小结
去强，即国家如何处理对抗法令的现象。大概如下：
1. 政令统一，降低执政成本
2. 拉平贫富差距
3. 国家聚集力量之后需要赢得对外战争，否则这股力量就会损害国家自身
4. 重刑轻赏。如果国家能够赢得对外战争，这样国家就会有资本来进行赏赐；而重刑可以使百姓远离犯罪，轻赏可以使得赏赐显得尊荣。

** 说民
用善，则民亲其亲；任奸，则民亲其制。

罚重，爵尊；赏轻，刑威。爵尊，上爱民；刑威，民死上。

故行刑，重其轻者，轻者不生，则重者无从至矣，此谓治之于其治者。行刑。重其重者，轻其轻者，轻者不止，则重者无从止矣，此谓治之于其乱也。故重轻，则刑去事成，国强；重重而轻轻，则刑至而事生，国削。

民勇，则赏之以其所欲；民怯，则杀之以其所恶。故怯民使之以刑，则勇；勇民使之以赏，则死。怯民勇，勇民死，国无敌者必王。

民贫则弱国，富则淫，淫则有虱，有虱则弱。故贫者益之以刑，则富；富者损之以赏，则贫。治国之举，贵令贫者富、富者贫。

刑生力，力生强，强生威，威生德，德生于刑。故刑多，则赏重；赏少，则刑重。

民之所欲万，而利之所出一。民非一，则无以致欲，故作一。作一则力抟，力抟则强。强而用，重强。故能生力，能杀力，曰攻敌之国，必强。塞私道以穷其志，启一门以致其欲，使民必先行其所要，然后致其所欲，故力多。力多而不用，则志穷；志穷，则有私；有私，则有弱。故能生力，不能杀力，曰自攻之国，必削。故曰：王者，国不蓄力，家不积粟。国不蓄力，下用也；家不积粟，上藏也。

国治：断家王，断官强，断君弱。重轻，刑去。...故有道之国，治不听君，民不从官。

*** 小结
这篇讲述了商鞅对于其法令的一些基本原理的解释，其中很多与当时国家的正常执政思维是有冲突的。

为什么举奸而不是举贤？因为用贤人百姓就会亲近人而不是政府，而用尖刻的人百姓就会亲近法令而不是人。

为什么重罚轻赏？因为这样会凸显出奖赏的贵重。

为什么对轻罪要施重刑？因为这样就会使百姓连轻罪都不敢犯，最终达到改变社会风气，使任何人都不犯罪的理想状态；如果对重罪用重刑，对轻罪用轻刑，那么百姓仍然会去试图犯罪。

如何能够集结百姓的力量？国家限制百姓只能以农业或者战争才能出人头地，这样虽然百姓的欲望很多，但是只能通过这一途获利，那么自然能够聚集力量；而且必须赢得对外战争的胜利，否则这股力量就会损害国家自身。

为何要用法治而不是人治？因为用法治可以使普通人也知道该如何做；每个人都知道如何做，那么治理效率就会大大提高。

** 算地
夫地大而不垦者，与无地同；民众而不用者，与无民同。故为国之数，务在垦草；用兵之道，务在壹赏。

民之性：饥而求食，劳而求佚，苦则索乐，辱则求荣，此民之情也。民之求利，失礼之法；求名，失性之常。奚以论其然也？今夫盗贼上犯君上之所禁，而下失臣民之礼，故名辱而身危，犹不止者，利也。其上世之士，衣不煖肤，食不满肠，苦其志意，劳其四肢，伤其五脏，而益裕广耳，非性之常也，而为之者，名也。故曰：名利之所凑，则民道之。

夫农，民之所苦；而战，民之所危也。犯其所苦、行其所危者，计也。故民生则计利，死则虑名。名利之所出，不可不审也。利出于地，则民尽力；名出于战，则民致死。

故天下一宅，而圜身资。民资重于身，而偏托势于外。

圣人非能以世之所易胜其所难也，必以其所难胜其所易。

资藏于地则朴，托危于外则惑。

故圣人之为国也，观俗立法则治，察国事本则宜。不观时俗，不察国本，则其法立而民乱，事剧而功寡。

夫刑者，所以禁邪也；而赏者，所以助禁也。

求显荣之门不一，则君子事势以成名。小人不避其禁，故刑烦。君子不设其令，则罚行。刑烦而罚行者，国多奸，则富者不能守其财，而贫者不能事其业，田荒而国贫。田荒，则民诈生；国贫，则上匮赏。

*** 小结
后面慢慢的有一些篇幅会与之前的理论有一些重合与补充。这篇主要论述的是为何要重农。人都为名利二字，生者为利，死后为名。所以要把百姓的名利所出都系在国内的土地上，否则百姓就会学习一身本领，这样所有国家对他们来说都能活，为什么还要为这个国家服务呢？

用赏赐辅助刑法，用重刑使人不敢犯禁，进而最终达到“去刑”的程度。如果刑罚不重，那么人们就会倾向于触犯刑罚，这样最终政府部门就会被这件事所拖累，而社会风气也不会向好。所以要“轻赏重刑”。

** 开塞
圣人不法古，不脩今。法古则后于时，脩今则塞于势。周不法商，夏不法虞，三代异势，而皆可以王。故兴王有道，而持之异理。

古之民朴以厚，今之民巧以伪。故效于古者，先德而治；效于今者，前刑而法。此俗之所惑也。今世之所谓义者，将立民之所好，而废其所恶；此其所谓不义者，将立民之所恶，而废其所乐也。二者名贸实易，不可不察也。

故王者刑用于将过，则大邪不生；赏施于告奸，则细过不失。

故王者以赏禁，以刑劝

*** 小结
又是一篇经典章节，不好摘，否则又要全摘下来。这篇实际上展开了《更法》篇中没说的法家的整个理论根本。尝试梳理：

-----
天地开而人生。人类一开始没有社会组织架构，大家行事的准则就是根据亲缘关系来定远近。大家都是自私的，那么当人越来越多之后，社会就会混乱，这时候就会出现谁的拳头硬谁就是老大的局面（就是原始的自然规则，弱肉强食）。

这时候贤人出现了。他们公正无私，以利他为己任，并且以推举的方式选出其他人（类似禅让、举孝廉）来作为仲裁人。这时，自私的思想被推崇贤德的思想所取代。但是随着人口更加多，这种方式也出现了弊端。因为下层的人毕竟不是贤人，他们没有准绳而贤人又肯定是不够的。

于是圣人出现了。他们指定了法律，并且设立了官职来维系法律，官员需要统一的领导，于是设立了君主。这时，推崇贤德的思想被尊重权贵的思想所取代。这三个时代虽然看起来思想是截然不同的，但实际上是当时的人根据社会的发展变化而做出的因地制宜的调整。

圣人不法古，不修今。效法古代和现代的其他例子都是不能很好的合乎自己的情势的。三代都是靠武力取得天下，而治理国家却都是用的仁义文教。

古代的民风淳朴，现在的百姓都很奸猾。所以上古用德治，而现在应该用法治。这是社会上所疑惑的地方。现在所谓的仁义之举，就是顺应百姓的喜好，而不义之举则是施行百姓所厌恶的措施。这两件事实际上是相反的（因为当世的民风是坏的）。所以我想用刑法来匡正民风，以复三代之治。

世间常用的手段是重罪重罚，轻罪轻罚；大功重赏，小功轻赏。但是这样刑罚并不能止罪，奖赏用在了促进仁义道德的上面也不会对犯罪有所作用。所以我认为应该对小罪用重罚，而赏应该用在告发犯罪方面，这样就会使任何人都不敢犯罪，这样小罪都没有人敢犯，那么整个社会的风气就会极大的提升。

君主是因为人多了混乱才诞生的，他的出现是与律法息息相关的。现在人们希望有君主但是却又希望能摆脱法律的束缚，实在是愚昧的。所以想要称王天下的君主一定会用法治来匡正社会的行为，用赏赐来禁止民众犯罪（而不是用来奖励所谓仁义），这样整个社会的风气就会好起来。
-----

其实商鞅的法治与儒家的德治所追求的理想都是一样的，只是途径不同。商鞅认为仁德这个东西你很难灌输给别人，社会上大部分人的品德都达不到贤者这个层面，所以只是靠道德标榜是很难复三代的。而仁德的人可以以律法的形式匡正整个社会的风气，规范每个人的行为，这样整个社会自然就会井井有条起来。“以刑劝”用太祖的话说就是“惩前毖后，治病救人”，与美帝所谓的“程序正义”层次差的实在太远。

** 壹言
夫民之从事死制也，以上之设荣名、置赏罚之明也，不用辩说私门而功立矣。

夫圣人之治国也，能抟力，能杀力。制度察则民力抟，抟而不化则不行，行而无富则生乱。故治国者，其抟力也，以富国强兵也；其杀力也，以事敌劝民也。

治国者贵民壹，民壹则朴，朴则农，农则易勤，勤则富。富者废之以爵，不淫；淫者废之以刑，而务农。故能抟力而不能用者必乱，能杀力而不能抟者必亡。故明君知齐二者，其国强；不知齐二者，其国削。

今世主皆欲治民，而助之以乱；非乐以为乱也，安其故而不窥于时也。是上法古而得其塞，下修令而不时移，而不明世俗之变，不察治民之情，故多赏以致刑，轻刑以去赏。夫上设刑而民不服，赏匮而奸益多。故民之于上也，先刑而后赏。

*** 小结
如何聚集民众的力量？使民众能够一心一意的从事农战就可以。如何做呢？以刑罚为手段使百姓平时从事农业生产，积聚了财富之后用爵位拉平贫富差距，使百姓一直较为贫穷（人富则淫）；然后以对外战争的手段使用力量，这样能够获取更多的土地财货来进行封赏。

** 错法
爵禄者，兵之实也。

三王五霸，其所道不过爵禄，而功相万者，其所道明也。是以明君之使其臣也，用必出于其劳，赏必加于其功。功赏明，则民竞于功。为国而能使其民尽力以竞于功，则兵必强矣。

人生而有好恶，故民可治也。

好恶者，赏罚之本也。

夫民力尽而爵随之，功立而赏随之，人君能使其民信于此如明日月，则兵无敌矣。

无私德也，故教流成。

故凡明君之治也，任其力不任其德，是以不忧不劳，而功可立也。

夫圣人之存体性，不可以易人，然而功可得者，法之谓也。

*** 小结
如何正确的使用法的力量？法本身就是利用人趋利避害的本性引导百姓的力量为国家所用。律法以国家的利益为出发点，即促农战，然后公正无私的执行，那么法就可以达到国家的目的而不必要求每个人都是圣人。

** 靳令
任功，则民少言；任善，则民多言。

民有余粮，使民以粟出官爵，官爵必以其力，则农不怠。

国以功授官予爵，则治省言寡，此谓以治去治、以言去言。

效功而取官爵，虽有辩言，不能以相先也，此谓以数治。

重刑少赏，上爱民，民死赏。多赏轻刑，上不爱民，民不死赏。利出一空者，其国无敌；利出二空者，国半利；利出十空者，其国不守。重刑，明大制；不明者，六虱也。六虱成群，则民不用。是故兴国罚行则民亲，赏行则民利。行罚，重其轻者，轻者不至，重者不来。此谓以刑去刑，刑去事成；罪重刑轻，刑至事生，此谓以刑致刑，其国必削。

圣君知物之要，故其治民有至要，故执赏罚以辅壹教，仁者，心之续也，圣君之治人也，必得其心，故能用其力。力生强，强生威，威生德，德生于力。圣君独有之，故能述仁义于天下。

*** 小结
如何能使政令贯彻呢？重刑少赏，赏罚分明，将力量集中于国家手中，不要任用那些所谓的能言善辩之士，赏罚都由事实为准。只有最终国家具有了力量，才能更好的申行仁义。

** 修权
国之所以治者三：一日法，二日信，三日权。法者，君臣之所共操也；信者，君臣之所共立也；权者，君之所独制也，人主失守则危。

凡赏者，文也；刑者，武也。文武者，法之约也。

故法者，国之权衡也。

不以法论知、能、贤、不肖者，惟尧；而世不尽为尧。

故三王以义亲天下，五霸以法正诸侯，皆非私天下之利也，为天下治天下。是故擅其名而有其功，天下乐其政，而莫之能伤也。今乱世之君、臣，区区然皆擅一国之利而管一官之重，以便其私，此国之所以危也。故公私之交，存亡之本也。

夫废法度而好私议，则奸臣鬻权以约禄，秩官之吏隐下而渔民。谚曰：“蠹众而木析，隙大而墙坏。”故大臣争于私而不顾其民，则下离上。下离上者，国之“隙”也。秩官之吏隐下以渔百姓，此民之“蠹”也。故有“隙”、“蠹”而不亡者，天下鲜矣。是故明王任法去私，而国无“隙”、“蠹”矣。

*** 小结
君主与法的关系是怎么样的呢？

法的能力来自于君主的“权”，而百姓对法的信任来自与政府的“信”。君主应该“民为贵社稷次之君为轻”，只有这样的法令才能申于天下。而严明的执行法律也可以杜绝大臣在中间鱼肉百姓，使君主的意志与百姓之间产生隔阂。

** 赏刑
壹赏则兵无敌。

夫明赏不费，明刑不戮，明教不变，而民知于民务，国无异俗。明赏之犹至于无赏也，明刑之犹至于无刑也，明教之犹至于无教也。

所谓壹赏者，利禄官爵抟出于兵，无有异施也。

善因天下之货，以赏天下之人。故曰：明赏不费。

故曰：重刑，连其罪，则民不敢试。民不敢试，故无刑也。

刑重而必得，则民不敢试，故国无刑民。国无刑民，故曰：明刑不戮。

夫故当壮者务于战，老弱者务于守，死者不悔，生者务劝，此臣之所谓壹教也。民之欲富贵也，共阖棺而后止，而富贵之门必出于兵，是故民闻战而相贺也，起居饮食所歌谣者，战也。此臣之所谓明教之犹至于无教也。

圣人治国也，易知而难行也。是故圣人不必加，凡主不必废；杀人不为暴，赏人不为仁者，国法明也。圣人以功授官予爵，故贤者不忧；圣人不宥过，不赦刑，故奸无起。圣人治国也，审壹而已矣。

*** 小结
所谓明赏不费，就是指能够正确的利用积攒起来的力量，攻城略地，这样奖赏就永远够用。
所谓明刑不戮，是指通过重刑使得百姓连小罪都不敢犯，这样重刑其实也就相当于没有。
所谓明教无教，是指通过刑罚规范人们的行为，使百姓只知道靠对外作战赢得富贵，这样就规整了人们的行为，国民一心。

** 画策
故以战去战，虽战可也；以杀去杀，虽杀可也；以刑去刑，虽重刑可也。

民本，法也。

凡战者，民之所恶也。能使民乐战者，王。

故善治者，刑不善而不赏善，故不刑而民善。不刑而民善，刑重也。刑重者，民不敢犯，故无刑也；而民莫敢为非，是一国皆善也，故不赏善而民善。赏善之不可也，犹赏不盗。

治主无忠臣，慈父无孝子

恃天下者，天下去之；自恃者，得天下。

仁者能仁于人，而不能使人仁；义者能爱于人，而不能使人爱。是以知仁义之不足以治天下也。圣人有必信之性，又有使天下不得不信之法。所谓义者，为人臣忠，为人子孝，少长有礼，男女有别；非其义也，饿不苟食，死不苟生。此乃有法之常也。圣王者不贵义而贵法，法必明，令必行，则已矣。

*** 小结
战争、杀戮、刑罚都是为世人所不齿的行为，但是在乱世当中，只有具有了强力才能最终终止战争、杀戮，以刑罚来匡正已经混乱邪恶的风气。因此，以法来做这些不齿的行为实际上正是符合当时形势的。所以，国家必须以法令为核心，根据时局对法令变更，以强制力为基础去匡正本国百姓的行为。

而法治的主要目的不是使原本的好人、贤人收到表彰，而是使原本的恶人、小人不敢作恶，以此来保护原本的好人。因为奖赏好人就像奖赏不偷东西一样，这是应该做的；而奖赏了好人并不会使坏人不作恶；而惩罚了坏人可以使坏人不作恶，另一方面可以使好人活得更好；也就是说好人并不会因为奖赏而受到什么影响，而坏人却会因为惩罚而使整个社会变得更好。所以赏赐告发，轻赏重罚才是最有效率的手段。

** 定分
故圣人为法，必使之明白易知，名正，愚知遍能知之；为置法官，置主法之吏，以为天下师，令万民无陷于险危。故圣人立天下而无刑死者，非不刑杀也，行法令，明白易知，为置法官吏为之师，以道之知，万民皆知所避就，避祸就福，而皆以自治也。故明主因治而终治之，故天下大治也。

*** 小结
这一篇最重要的地方就是商鞅的法与当今法的很大一点不同，即商鞅的法要简要明晰，即使愚笨的人也能理解；而当今的法条繁复，除了专业的律师谁都不知道具体的法令如何。
普通人都能懂法的好处是极大的降低了管理成本，实际上并不是为了惩罚，而是为了使每个人都知道如何做才是正确的，最终能达到“去法”的目的。

* 总结
商鞅变法是中国历史上少有的成功的变法。仅仅用了二十年的时间使秦的国力一跃赶超山东六国，简直令人惊叹。“商君佐之，内立法度，务耕织，修守战之具，外连衡而斗诸侯”，秦以此为转折点，一百多年后终于经由始皇帝“奋六世之余烈，振长策而御宇内，吞二周而亡诸侯，履至尊而制六合，执敲扑而鞭笞天下，威振四海”。其很多手段在当今看来还是非常激进的，但如果我们不带着所谓“现代人”的有色眼镜去看的话，能够看出商鞅的变法其立意之高远，效果之显著，思维清晰，逻辑顺畅，令后人敬佩。

商君书里有几个重要的概念，贯穿始终。首先是“壹”，即统一、专一、始终。只有这样，百姓、国家才能同步，不会因为朝令夕改，或者王子犯法与庶民不同罪等而对法令的执行发生质疑，这样国家做任何事百姓才会响应，政令的效果才能最大的达成。
其次是农战。商鞅变法的核心就是强国，而战争是战国时期绕不过去的槛。而农战本身是百姓所厌恶的事，因此如何使百姓能乐农乐战就成了变法的核心问题之一。
其次是法。商鞅的法只是手段，是为能够最高效的贯彻统治者的意志而存在的，它不是目的，这与美帝当今的程序正义完全不同。商鞅的法最终的目的是“去法”，即让所有人都能够知道正确的行为规则是什么并且遵守，最终达到与儒家“复三代之治”相同的目的。

法家与儒家最大的不同就是求变，一般都是面临危亡的时候才会选择法家而暂时抑制儒家。“圣人不法古，不修今。”成为千百年来变法的战斗口号。为什么求变才用法呢？因为用法效率最高，可以将统治者的主观意志以法令的形式客观的施行在整个国家。而变法必然会触及既有利益阶层的反抗，因此我们可以看到一代代的法家名士下场凄惨。

商鞅变法最重要的是加强了秦国的社会动员与组织能力。商鞅利用人趋利避害的特性，灵活运用赏罚的手段，使百姓都能务农战而轻商贾、读书，加强了国家力量；同时以公正的法令执行弱化了君权与百姓之间的大臣阶层，间接加强了君权。而其“以法去法”的“道”颇有辩证唯物主义的东西在里面。
