#+TITLE: 你不懂咖啡 总结
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2018-11-01 13:25>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

喝了这么多咖啡，还是觉得家里20块钱一斤的大叶子茶好喝。

#+END_COMMENT

咖啡树需要三年的生长时间才开始开花，主要分布在赤道南北纬25度之间的热带区域。

 | 名称     | 原产地     | 特性                                                                                          |
 | 阿拉比卡 | 埃塞俄比亚 | 主流，全世界65%的产值。需要肥沃的酸性土壤，不需要阳光直射，日照强的地方还需要专门种植“遮荫树” |
 | 卡内弗拉 | 维多利亚湖 | 抗病强，抗旱差，但对土壤要求低。咖啡因含量更高，苦味较重，有独特的大麦茶香                    |

* 咖啡因
无论深度烘焙还是轻度烘焙，咖啡因的含量是不变的，所以如果使用同样的量冲泡咖啡，咖啡因的量也是不变的，因为虽然烘焙会减少咖啡因，但是咖啡豆自身的重量也会减少。

* 苦味
咖啡因只占苦味的10%；咖啡苦味的根源之一是褐色色素，大分子褐色色素的苦味更强。随着烘焙程度的加深，褐色色素的量会增加，大分子褐色色素的比例也会增加。所以，深度烘焙的咖啡豆的苦味和质感更强；另一个原因是氨基酸与蛋白质加热后形成的“环缩二氨酸”，可可、黑啤中也有此种成分。

* 酸味
主要来自烘焙过程中产生的奎宁酸。酸味随着烘焙会增加，但是之后随着温度更高又逐渐减少。冲好的咖啡会随着时间过去逐渐释放出酸味来。
如果用弱碱性的矿泉水可以中和咖啡中的酸味。
随着烘焙的加深，酸味会降低，苦味会增加。

* 甜味
越成熟的生豆蔗糖含量越高，但是会随着烘焙逐渐消失，形成咖啡颜色、香味、酸味的来源。果实成熟度越高，烘焙时越容易着色，也就越容易形成香味与酸味丰富的咖啡。

* 香味
美拉德反应，同酱油、烤肉、烤面包类似。
焦糖化。
如果手头的咖啡豆味道不太好，可以用平底锅将其稍微煎一下再品尝，就会发现味道变好了。

* 咖啡色
生豆是淡绿色，烘焙之后变成咖啡色，以低聚糖、氨基酸、绿原酸形成。色素是苦味的主要来源，色素分子越大，咖啡越苦。
咖啡因与绿原酸类含量较高的咖啡比较容易浑浊，因而一般来说卡内弗拉种要比阿拉比卡种更浑浊一些。

* 温度
如果温度低，我们对苦味和甜味的感觉会下降，而对酸味的感觉会敏感，所以冰咖啡更酸。

* 劣化
烘焙过的咖啡豆放久了会发生“劣化”，即二氧化碳会带走香味。
咖啡粉比咖啡豆劣化速度快很多，所以咖啡粉比咖啡豆的香味差很多。

* 萃取
萃取时，以下因素会对咖啡的味道产生影响：
1. 水温（和咖啡粉接触时的水温）。
   由于酸味溶解的速度快，受温度影响小；而苦味在水温高的时候溶解速度加快，因而水温高的时候咖啡中的苦味比例会增加。
2. 时间（水与咖啡粉接触的时间）。
   苦味溶解慢，所以增加萃取时间，咖啡苦味会增加。
3. 咖啡粉颗粒的大小。
   酸味易溶，但咖啡粉颗粒小会加快苦味的溶解，因而颗粒越小越苦。

* 冰滴咖啡
以常温的水来冲咖啡，需要浸泡几小时甚至十几小时。特点是味道温和，苦味、香味都较淡。

* 冰咖啡
优点是温度低，咖啡风味持续时间长。
由于温度低人们对甜、苦的敏感度下降，对酸味敏感度上升，因而制作冰咖啡需要烘焙程度较高且卡内弗拉种混合比例较高的咖啡豆，这样就可以弱化酸味、强化苦味。
