#+TITLE: 《六韬》 读后总结
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2019-10-03 22:05>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

是故人君从事于富。不富无以为仁，不施无以合亲。

#+END_COMMENT

* 摘抄
** 文韬
臣闻君子乐得其志，小人乐得其事。今吾渔甚有似也，殆非乐之也。

缗微饵明，小鱼食之；缗调饵香，中鱼食之；缗隆饵丰，大鱼食之。夫鱼食其饵，乃牵于缗；人食其禄，乃服于君。故以饵取鱼，鱼可杀；以禄取人，人可竭；以家取国，国可拔；以国取天下，天下可毕。

天下非一人之天下，乃天下之天下也。同天下之利者，则得天下；擅天下之利者，则失天下。天有时，地有财，能与人共之者，仁也。仁之所在，天下归之。免人之死，解人之难，救人之患，济人之急者，德也。德之所在，天下归之。与人同忧、同乐、同好、同恶者，义也；义之所在，天下赴之。凡人恶死而乐生，好德而归利，能生利者，道也。道之所在，天下归之。

祸福在君，不在天时。

见善而怠，时至而疑，知非而处，此三者，道之所止也。

一曰仁，二曰义，三曰忠，四曰信，五曰勇，六曰谋：是谓六守。

富之而不犯者，仁也；贵之而不骄者，义也；付之而不转者，忠也；使之而不隐者，信也；危之而不恐者，勇也；事之而不穷者，谋也。

日中必慧，操刀必割，执斧必伐。

是故人君从事于富。不富无以为仁，不施无以合亲。

故天下治，仁圣藏；天下乱，仁圣昌；至道其然也。

君以世俗之所誉者为贤，以世俗之所毁者为不肖，则多党者进，少党者退。若是，则群邪比周而蔽贤，忠臣死于无罪，奸臣以虚誉取爵位，是以世乱愈甚，则国不免于危亡。

凡用赏者贵信，用罚者贵必。

凡兵之道莫过乎一，一者能独往独来。黄帝曰：‘一者阶于道，几于神’。用之在于机，显之在于势，成之在于君。故圣王号兵为凶器，不得已而用之。

*** 注释
而吾则以圣人之权托于此也。太公之遇文王，或以为屠，或以为渔，不足疑也。意其穷时无所不为也。

昔诸葛亮人问其志，则笑而不言。及遇先主，一话草庐之间，而三分基业已定，则君子之至必期有得也。

太公之志，非乐渔也。寓于此而期于彼也。古者未行道之际，而求以行之，其志各有所乐也，初不在于物也。阿衡负鼎，百里饭牛，彼其志各有所得也，岂非乐邪？亦权之所寓也。若夫小人则唯其所作，乃其所乐也。故小人乐得其事，君子之所为必有似也者，以其事在此而意在彼也，非乐于此也。

志者一人之所独，果决而不回者也；情者万物之所同，感通而无所阻者也。

彼惟有所贪，故必有所制，所以皆可取也。

圣人之德诱，此‘诱’字于循循善诱同解，皆使人心悦诚服而不自知也。

打一个比喻来说，这一篇所记载的也就是太公与文王第一次会晤时所提出的‘隆中对’……可以把本篇看做是周灭商的政治纲领和战略决策。

直斥龟蓍为‘枯草朽骨’，‘何以辨吉凶’。

中国，本也；四夷，末也；农桑，本也；技巧，末也。不治中国而治四夷，则内虚矣；不务农业而务技巧，则无储矣。

事不可以不防微。

** 武韬
天下者，非一人之天下，乃天下之天下也。取天下者，若逐野兽，而天下皆有分肉之心；若同舟而济，济则皆同其利，败则皆同其害。

鸷鸟将击，卑飞敛翼；猛兽将搏，弭耳俯伏；圣人将动，必有愚色。

大盖天下，然后能容天下。

民如牛马，数喂食之，从而爱之。

心以启智，智以启财，财以启众，众以启贤，贤之有启，以王天下。（用思考开启智慧，用智慧开启财富，用财富赢得民心，用民心赢得贤才，能够拥有贤才，就可以依靠他们称王天下了。）

** 龙韬
所谓五材者，勇、智、仁、信、忠也。勇则不可犯，智则不可乱，仁则爱人，信则不欺，忠则无二心。

士未坐勿坐，士未食勿食，寒暑必同。如此，则士众必尽死力。

故杀一人而三军震者，杀之；赏一人而万人说者，赏之。杀贵大，赏贵小。

将与士卒共寒暑，劳苦，饥饱，故三军之众，闻鼓声则喜，闻金声则怒。城深池，矢石繁下，士争先登；白刃始合，士争先赴。士非好死而乐伤也，为其将知寒暑、饥饱之审，而见劳苦之明也。

用兵之害，犹豫最大；三军之灾，莫过狐疑。

因其惊骇者，所以一击十也；因其劳倦幕舍者；所以十击百也。

战必以义者，所以励众胜敌也；尊爵重赏者，所以劝用命也；严刑重罚者，所以罢怠也。

** 总结
《六韬》又称为《太公兵法》，以姜子牙与周文王、周武王的问对为形式，描述了如何识人、立将、战争等治国方略。一般认为成书于战国晚期，作者不详。

六韬分为文韬、武韬、龙韬、虎韬、豹韬、犬韬，其中文、武韬讲述的是国家战略层面的问题，龙韬讲述的是如何选将等战争方面的战略问题，后三韬更多的是实际作战时的战术处理，因此对今人来讲参考价值也更小。

与《商君书》相比，这本兵书的思想更贴近我国古代“正统”思想，即强调君主仁德的作用，强调“天下者，非一人之天下，乃天下之天下也”；当然与腐儒不同的是，书中强调了“利”，从《文师第一》就在强调：

“夫鱼食其饵，乃牵于缗；人食其禄，乃服于君。”
“凡人恶死而乐生，好德而归利，能生利者，道也。道之所在，天下归之。”
"是故人君从事于富。不富无以为仁，不施无以合亲。"

也就是说，既要面子又要里子，道术是相辅相成的，既要讲理想，又要讲物质。

在战争上，除去局限于当时的一些战术描述，书中主要描述了：
1. 如何择将，也就是“勇、智、仁、信、忠”
2. 身先士卒的重要性
3. 作战时机的重要性
