#+TITLE: 赢 读后总结
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2020-01-11 17:18>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

Life is not easy for any of us. We must work, and above all we must believe in ourselves. We must believe that each one of us is able to do some thing well. And that we must work until we succeed.

#+END_COMMENT

* 摘抄
** 基础篇
*** 使命和价值观
因为公司管理层都明白，如果在经济效益上不能取得成功，那么其他任何社会目标都将是奢谈。

要想让价值观真的被大家所重视，公司应该奖赏那些品行 突出、实践了价值观的员工，而“处罚”那些与之相悖的人。请相信我，这有助于企业的成功。

*** 坦诚
从我加入GE的那一天，一直到被任命为CEO的时候，在整整20年的时间里，我的老板们经常告诫我不要过分直率。我被归入粗暴无礼的类型，总有人警告我，过分直率很快会妨碍自己的事业。

*** 考评
归根到底，所谓的区别考评制度不过是指资源配置而已，这正是企业领导者要做的事情，而且也是他们得到自己报酬的首要原因之一。

在GE，“优势业务”意味着某项产业在其市场上占据第一或第二的位置。

在GE，我们制订了“达到行业里数一数二”的目标考核体制，从而终结了几十年以来四处撒钱的恶行。

它是这样一个过程，要求经理们根据业绩表现把自己的员工划分为以下三个类别：最好的20%、中间的70%以及最差的10%。

区别考评制度只奖赏那些值得受到奖励的团队成员。顺便说一下，对这样做感到不满的只有表现不佳的人。对其他的任何人来说，这个制度都是公平合理的。

我不知道这是件好事还是坏事，但一般来说，这个世界总是偏爱那些积极向上、性格外向的人。

但是，在区别考评的时候，所有的人都是靠业绩说话的，在这方面人人平等。

** 公司如何才能赢
*** 领导力
在你成为领导以前，成功只同自己的成长有关。
当你成为领导以后，成功都同别人的成长有关。

在担任领导的时候，你无论如何都不可能达到尽善尽美，而只能争取做得更好。

记住，在所有这些邂逅中，评估和引导都是重要的，但帮助下属树立自信心却可能是你应该做的最重要的事情。

不必多说，领导者需要为团队制订一个梦想，而且也应该这样做。

你必须坚持不懈地谈论自己的梦想—脱口而出，简直要说到被别人当成是废话的地步。

有些时候，我自己也曾在一天之中谈论了无数次关于 GE 的努力方向的问题，以至于再听到那个话题时都感到恶心。但是我认识到，这个信息对周围的某些人来说依然是新鲜的。因此，你需要不断地重复。

一个整天都保持着积极、乐观态度的经理，不知何故就带出了一个散发着进取、向上精神的团队或组织。

可是，作为领导者，你的工作就是同消极的引力做斗争。这并不是意味着让你去粉饰大家面对的艰巨挑战，而是说你要呈现出一种克服困难的、积极的、无所不能的态度。这意味着你要走出办公室，深入到大家中间去，真正关心他们在做什么，进展如何，带领大家一起翻越高山。

你的员工始终应当知道，自己的业绩表现如何，公司的业务进展怎么样。

请记住，担任领导并不意味着给你授予了王冠，而是给你赋予了一项职责—使其他人身上最好的潜质发挥出来。为了实现这个目标，就必须让你的员工信赖你。假如你能表现出坦诚、守信、实实在在的品质，那么他们会的。

你被选做一名领导，是因为你阅历丰富，做对事情的时候更多。因此，要学会倾听自己的直觉，它会告诉你某些东西。

而如果你是一个领导，那么你分内的工作则成了提出各种问题。你必须做好思想准备，要显得是部门中最无用的人。每次对一项决策、一项提议或一条市场信息进行讨论时，你都要一个劲地提问：“如果……会出现什么情况呢？”“为什么我们不……呢？”以及“怎么样才能……？”

对于自己的错误，你没有必要念念不忘，或者感到伤心郁闷。

你们进行了充分的庆祝吗？

这个人看上去诚实吗？她愿意公开承认自己的错误吗？

*** 招聘
随着生活经验的累积，我们中的许多人逐渐培养出了对正直的本能感应，在需要使用它的时候请不要犹豫。

而是指他们有一种强烈的求知欲，有宽广的知识面，可以在今天这个复杂的世界里与其他优秀的人一起工作，或者领导他们。

我要强调的是，应试者的教育程度只说明了一部分问题，尤其在智慧方面。

成熟的人知道尊重别人的情感，他们充满自信但并不傲慢无礼。

在任何层次的经理人中间，最糟糕的那种类型就是迟疑不决的人，他们总是说：“把事情推迟一个月，我们再好好地、认真地考虑一下。

你可以拥有积极向上的活力，懂得激励自己周围的每一个人，能够做出坚决的判断，但你可能依旧不能跨越终点。执行力是一种专门的、独特的技能，它意味着一个人要知道怎样把决定付诸行动，并继续向前推进，最终完成目标，其中还要经历阻力、混乱，或者意外的干扰。有执行力的人非常明白，“赢”才是结果。

同样重要的是，真诚可以使领导者显得和蔼可亲—姑且这么说吧。他们的“真”体现在同别人的交流过程中，体现在他们的感情里。他们话语令别人感动，他们传达的信息能够触动人们内心深处的某种东西。

一位优秀的领导者就要有这样的勇气，他敢于把最优秀的人集中到自己的团队里，而不怕把自己变成会议室里看上去最傻的人！

我特别喜欢那些曾经被完全击倒，却又能站起来，并且在下一个回合里能以更强的姿态出现的人。

如果某位值得信赖的同事告诉你，他对某个求职者有不好的直觉，那你应该认真倾听。

在面对工作的困难时，优秀的应试者会激动起来，表现出很强的好奇心和坚定的自信，而不是过于热心地对你所有的话都表示顺从。

在招聘员工时，不要给他们提供职业生涯的“终极职位”，除非这个位置是一个职能部门的负责人或者 CEO 。

可是要记住，每次在人员招聘上的失败都是你自己的责任。

如果在面试过程中我只能了解到应试者的一个方面，那我希望知道，他离开自己原来的职位的原因，以及上一次离职的原因。

*** 人员管理
在过去一年里，有多少人接受过面对面的、诚实坦白的业绩反馈会谈？

应当保证，经理人对员工的考评每年至少有一次，最好是两次，采取正式的、面对面会谈的形式。非正式的评价应当随时进行。但是在正式会谈时，应当让员工知道，与周围的人相比，他们处在什么样的位置上。如果你的企业希望推行区别考评制度，那么一个良好的业绩考评体系将为其奠定坚实的基础。

最后，一个好的评价体系应当包括关于职业发展的内容。经理人不但应当跟自己的人员谈未来的职业发展规划，而且应当提出两三个员工的名字，也就是他们认为在自己高升以后有可能替代他们的员工。

要想激励人们上进，就需要在奖励和认同上面表现出差别。

如果可能的话，公司的内部培训应该请自己的高层经理人来主持，他们不但要以教师的身份为大家服务，而且还可以担任角色扮演者。

这样的工作可不能有名无实，而是每当明星人物出现骄傲自大或者失控的苗头时，就需要有人出面，同明星人物就公司的价值观和行为模式问题进行坦诚的谈话。你决不能害怕自己的明星人物，他们不应该把离开公司当成要挟的筹码。

最理想的做法是，在这位明星宣布离开的8小时之内，任命他的替代者。不错，8小时。这个迅疾的行动会把信息明确传递给整个公司－－没有人是公司离不开的，没有哪个个人能够凌驾于公司之上。

要想快速替换明星人物，唯一的办法就是有充足的替补队员。这也就要求公司有良好的业绩评价体系，特别是帮助员工制订长远的职业发展规划。认真做好这样的工作，可以使你在面临任何明星离开的问题时，能够迅速从公司内部找到一两名优秀的候选人。

未来的明星们常常埋藏在中间的70%里面，努力而默默地工作。

你的公司应该尽量扁平化。对经理人汇报的直接下属至少应该为10个人，如果他们有丰富的管理经验，还可以增加30%-50% 。

*** 分手
你的工作就是尽可能多地搜集这些信息，然后尽可能清晰和及时地传达给自己的员工。如果能这样，那么一旦发生裁员的情况，至少你少下的员工能有一定的准备。

一个好的业绩评价方法能够给员工提供正确的信息，让他们提前做准备－－这是我所知道的最开放、最公平的办法。

*** 变革
如果你想在商业游戏中继续玩下去，想要“赢”，就必须拥抱变革。

*** 危机管理
对于公司的行为准则、规定和监督办法，进行再多的培训都是可以的。

公开讨论出现的问题，把自己的立场讲清楚，向大家解释问题出现的原因和你将如何进行处理。

正像遭遇大规模的公开危机一样，永远不要忘记，这件事情需要有人来妥善处理。要确保自己在行动。

** 如何赢得竞争
*** 战略
如果你的企业是个学习型的组织，人们渴望每天都能把一切做得更好，那你的战略就能充分发挥其威力。员工们会从各个地方学到最好的技能，不断提高企业的效率水平。

要想找到正确的战略，你必须假定对手都是非常出色的，或者至少与你自己同样出色。他们的动作也非常快，甚至更快。

在预测未来的时候，再极端的偏执想法都不过分。

组织都知道，哪些人是重要的，只有让这些重要的人去领导新的战略，计划才能得以实施。

适合在这个行业奋斗的人是勤奋、严谨、关注细节的。他们不是梦想家，而是团结的战斗队。

但是最后能赢的公司要做两件事情：模仿，并且改进。

事实上，战略实施的第三步完全是发现最佳实践经验，借鉴它们，然后不断地进行改进。如果你能做得很好，那将与创新没有什么不同。

找准正确的方向，把合适的人放到合适的位置上，然后疯狂地工作，比别人都做得更好，继而每天都去寻找和改进最好的实践经验吧。

*** 预算
设备部门的利润要低于计划，与去年相比也没有增长。但是该部门的表现（在艰难的环境中）与其主要对手相比却是非常出色的，惠而浦和梅泰格公司的业绩要更加糟糕。

一定不要放弃，这太重要了。

*** 有机的成长
要让新业务发展下去，就必须让最出色的人来执掌，而不是最平凡的人。

即使要面临这样的风险，你还是要为新项目的前进而努力宣传－－夸大其词地宣传。因为如果你不这样做，新项目就会先天不足。如果你这样做了，但项目依然失败，那也该承认自己曾起过的作用。你相信某个项目会赢，但最后没有成功，这不足为怪。

在理想情况下，配备有强大领导者的新项目应该拥有所有的生产工具，例如建立独立的研发、销售和营销队伍。他们有权自己主宰人事和战略方面的重要决定。

要想得到自由度，最好的途径就是用自己的表现去争取它。如果你做事尊重规则，你就可以很快得到自由。公司的焦点本来就集中在你身上，如果你感觉到原来对你的限制让人难受，也不要反应过激。这需要一个过程，就像你的父母让你独立生活时一样。

抓住这些机遇。挑选有激情、有魄力的人来负责，给他们你所有的资源，给他们足够的空间。

*** 企业并购
任何收购的目标之一都是寻求更好的人才。

要把并购想象成获得人才宝库的机会－－这种机遇是难得的，在其他情况下，你需要经过多年的寻找，向猎头公司支付无数费用才能得到。

当你有两个人做同一件事请时，如果他们的能力在其他方面都很相近，则态度更积极的、支持合并的人会赢。

*** 六西格玛
我总是告诉别人，变化是件好事，并且要让变化改造自己。

如果在服务和产品上不能保证品质始终如一，必将扼杀顾客的忠诚。

** 个人职业生涯如何才能赢
*** 合适的工作
重要的一点是，你在未来会从事什么样的工作，这个问题几乎是不可能准确预测的。

你只需要记住，说自己并不在乎财富，听起来的确很高尚，但要在今后的岁月里为职业决定的后果承担责任，则是完全不同的事情，特别是当你需要为家庭支付房款和学费以后。

在职业生涯中，你也需要找到与自己志趣相投的人，而且越早越好。

换句话说，任何新工作都应该让自己感觉有所发展，而不是刚刚够用。

因为发展、成长、学习能让你全心投入、充满活力，让工作变得更加有趣，刺激你力争上游。

他的经历，与其他许多人的一样，告诉我们当面对那些一开始显得非常艰巨的工作时，你不应该害怕。如果你有某些长处－－那正是你被别人聘用或者提升的原因，那么你就可以在工作中获得成长，并随着经验的积累而变得更加出色。

我告诉他们，应该多关注那些处在生物技术和信息技术交叉领域的产业，应该尽可能学习任何与中国有关的知识，因为这个国家将在他们的有生之年渗透到方方面面的商业生活中。

如果义无反顾地去了，那将是个伟大的抉择。如果你不能去，也该把原因想清楚，保持内心的平静。

但对于最理想的工作而言，你应该是热爱它的－－至少是热爱其中的某些部分，工作能让你感到兴奋。与顾客打交道、商务旅行、每周二上午销售会议上的友善气氛，或者无论其他什么－－工作中总有些事情让你每天都渴望回到这里。

我以前也说过，每个工作都有起伏，但如果一份工作不能让你兴奋－－只是由于工作内容乏味－－那你就没必要在沉浸其中了。同时，也不要担心自己什么时候才能找到一份有意义的工作。
因为你能感受到它的存在。

如果你想寻找更好的工作，那么最快捷的方法就是在原先的岗位上干出出色的成绩。

我浪费了太多的时间，没有及时打发掉那两个不能完成任务的下属。

辩解，会让自己陷入沮丧。

*** 晋升
我喜欢承担更多的责任，做更大的生意，建造更大的厂房，管理更多的下属。

要交出动人的、远远超出预期的业绩；在机遇来临的时候，要敢于把自己的工作责任扩展到预期的范围之外。

不要麻烦你的老板动用政治资本来帮助你。

改变自己的工作方式，让你周围的人都能干得更出色，让老板更有面子。

谦虚点说，我的老板和副总裁感到非常震惊。他们对此事的积极反应让我明白，向别人交出超过预期的业绩将产生很好的影响。

“我想，纯粹是由于坚持，”他说，“我感到，我们必须变得更加自信一些。如果我们还是像通常那样循规蹈矩，即使能把生意做到一定的规模，也永远不会有大的突破。”

你可以确信，当人们谈论他的时候，没有人需要动用什么政治资本，所以他的职业生涯自然步步高升。

关键点在于：别让你的老板非要追根问底，你才把情况讲出来。如果想表现出一种能让人接受的个性，想让你的老板更轻松一些，那就要开放一点，有话直说。

要知道，想在同僚们一致的反对声中推荐某个人将是非常困难的。

这样，在晋升机会来临的时候，下属们对你的评价将是最为有利的：你很公正、很认真，你对他们是严厉的爱。

我不敢保证这些下属们都喜欢我—因为我做事太严厉，又很缺乏耐心。但是，我想他们一定很尊重我，因为我也非常尊重他们。

但无论如何，我还是认为财经媒体是位优秀的教师，每当我遇到一位不关心财经媒体的年轻人，我都会感到诧异。请不要再有眼无珠了—导师就在那里等着你的请教呢。

技能是重要的，但理想更为关键。

“成功，”吉米说，“在很大程度上取决于态度。”

“我想说，我获得晋升的主要原因是我用自己的业绩、态度和坚忍打动了每一个人。我从来没有放弃。”

*** 糟糕的老板
拜托！
与自己生活中可能遇到的其他一切不幸或者不公平的事情一样，为某个难处的老板工作是你面临的现实问题，而你必须解决它。

不要考虑太多，你只需要理解，自己是经过了权衡之后决定与一个坏老板待在一起的。这也就意味着你已经没有了抱怨的资格。

一旦你拥有自己的选择，就要同时承担后果。

*** 工作与生活的平衡
就个人而言，我认为在周末加班是非常惬意的，我们可以用更加轻松的方式来总结一周的成果，同时闲扯一些有关体育比赛的消息。

工作与生活的平衡其实是件奢侈品－－只有那些“有能力”用时间来换金钱或者用金钱来换时间的人才消受得起。

每天他都很早到办公室，但却坚持在6点准时下班。工作时间里他也很少卷入可能降低效率的闲聊，他总是显得很酷、很有效率。

是的，老板会同意给一些人有弹性的上下班时间表，但前提是他们必须保证自己的业绩。

尽管我们已经开发了许多新技术，让虚拟办公成为可能，但大多数经理人还是对提拔自己在战壕里结识的人感到更有把握，也就是指，那些他们能在会议室或走廊上见到的人、一起经历了危机考验的人。

"我知道，假如自己真的需要，公司是能够给我一定的弹性安排的，那是我多年的出色表现和投入所取得的回报。"

这意味着在你考虑工作和生活平衡的问题时，要清楚在绝大多数公司里，你需要通过努力去赢得弹性，而这个过程要花费时间...实际上，很多人觉得这种付出与获得的交换非常公平。

在任何组织里，最优秀的20%的人几乎从来不会抱怨工作与生活的平衡问题。这个事实肯定与他们的本性有关。

归根结底，大多数老板都认为工作与生活的平衡是你自己需要解决的问题，而不是他们的问题。

但是，你越是把工作与生活混淆在一起，你的感觉就会越麻烦、越混乱、越难以收拾。

我们都知道有些表面上非常开心的人，他们同时承担了巨大的事业和家庭的压力。

但如果你的计划不能使自己快乐，那么这个世界上所谓的平衡不过是尽义务而已。有一天，你会清醒过来，发现自己在一种特别的地狱里：周围的人都很快乐，而自己却异常孤独。
这对别人来说其实也不好。

** 有关赢的其他问题
*** 问题无处不在
首要的一点，就是启动三架保证竞争力的老战车—成本、质量和服务—并且让自己的驾驭技术更上一层楼。你要让组织里的每个人都能正确看待它们，把它们当成生存的要素。

要让他们告诉街上的陌生人，你的服务有多棒。联邦快递公司与戴尔公司就是光荣的榜样。

如果你希望得到晋升，最好的选择就是拿出更好的业绩，仔细地管理好下属，同样仔细地对老板负责，尽早参与公司的主要项目，争取大家的关注，珍惜许多良师益友的忠告；还有，总是对生活和工作保持积极向上的态度。同时，不要有劳你的老板动用政治资本来扶持你。即使出现难免的挫折，也不要动摇自己前进的决心。

它们都强调，成功是一个函数，它的影响因素包括才华、活力和雄心—这都是精英人士的特征。

假如说，未来的人们能够记起有关我的什么事情，那我希望是，我曾帮助人们认识到，优秀的领导可以为其他人的成长和成功助一臂之力。再重复一下，领导者不应该只管自己，而是要影响其他人。

* 总结
作者杰克韦尔奇，45岁的年纪便成为了GE CEO，20年时间塑造了GE的辉煌，被称为“世界第一CEO”。

什么是管理？管好资源，理顺流程，做好奖惩。公司的目的是为社会提供产品与服务，并且在竞争中保持不败。竞争的终极目的是实现垄断，在此之前都需要保证三个要素来保持竞争力：成本、质量和服务。

什么是领导？就是那个需要带领周围人前进的人。不同的人会有不同的领导风格，但好的领导却都具备类似的特性或者说素质：
1. 带领周围的人前进
   为着领导,必须有预见；没有预见，就没有领导。能够提前看到问题，能够防患于未然，是领导首先应该具备的能力。利用自己长久以来训练出的经验，帮助团队去解决问题吧。
2. 帮助周围的人成长
   在你成为领导以前，成功只同自己的成长有关；当你成为领导以后，成功都同别人的成长有关。不要怕做团队里那个最无能的人，周围的人成长了才能带来团队整体的成长，这是无与伦比的功勋。
3. 乐观的性格
   作为领导者，工作之一就是将无所畏惧的、积极的心态感染到团队。工作中总是有太多太多的事是负面的，而按照熵理论，任何事物都倾向于混乱，而不是有序。为了做成一件事，需要团队，特别是领导者付出很多很多努力，去跟各种人战斗。而团队没有乐观的性格，是很难去持续面对困难的。
4. 诚恳
   巧诈不如拙诚,惟诚可得人心。只有诚恳的与团队交流，分享自己的想法，才能真的得到与你共同前进的战友。
5. 执行力
   "你可以拥有积极向上的活力，懂得激励自己周围的每一个人，能够做出坚决的判断，但你可能依旧不能跨越终点。执行力是一种专门的、独特的技能，它意味着一个人要知道怎样把决定付诸行动，并继续向前推进，最终完成目标，其中还要经历阻力、混乱，或者意外的干扰。有执行力的人非常明白，“赢”才是结果。"

"找准正确的方向，把合适的人放到合适的位置上，然后疯狂地工作，比别人都做得更好，继而每天都去寻找和改进最好的实践经验吧。"
