#+TITLE: 读 How Google Works 总结
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2018-05-27 07:35>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

用户至上、目标远大、不畏失败

#+END_COMMENT

* 摘录
** 序言
如果只求渐变，时间一长，企业就会逐渐落伍，科技行业尤其如此，因为外界改变通常是革命性的，而不是循序渐进的。所以，你需要强迫自己着眼于未来。
** 前言
两人觉得，如果谷歌能提供优质服务，那么资金问题就能迎刃而解；如果两人一心专注于打造全球最棒的搜索引擎，那么成功就是迟早的事。
时至今日，我们的经验是，谷歌的员工中至少要有一半是工程师。
拉里所说的工程师都是杰出的程序员和系统设计师，但除了技术方面的资深经验之外，很多人还具备敏锐的商业头脑，在创意上也是才思泉涌。
而我们同时也明白，要在产品上追求卓越，最佳的途径并非靠商业计划，而是要尽可能物色最顶尖的工程师，给他们空间让他们尽情发挥。
如果某行业产品主要要素的成本曲线下降，那么该行业必将会出现剧变。
如果你的产品或服务欠佳，那你就处境危险了。
这些都是谷歌的产品，虽然各有特点，但没有一款能够深入人心。究其原因，就是这些产品都不够优秀，死得其所。
这就造成在传统企业中，多数知识工作者要么是技术达人、管理白痴，要么就是管理专家、技术菜鸟。

如果我们把传统知识工作者与谷歌十几年来招徕的工程师等人才放在一起对比，就会发现谷歌的人才是一个截然不同的员工群体。这些人并不拘泥于特定的任务，也不受公司信息和计算能力的约束。他们不惧怕危险，即使在冒险中失败，也不会受到惩罚或牵制。他们不被职位头衔或企业的组织结构羁绊住手脚，甚至还有人鼓励他们将自己的构想付诸实现。如果出现不同意见，他们不会选择缄口不言。他们很容易失去耐心，经常变换职位。他们具有很多领域的能力，经常会将前沿技术、商业头脑以及奇思秒想结合在一起。换句话说，至少从传统意义上来说，这些人已经不能算是知识工作者了。这是一个新的物种，我们称之为“创意精英”，他们，便是互联网时代取得成功的关键所在。

所有的创意精英都必须具备商业头脑、专业知识、创造力以及实践经验，这些都是基本特质。
无论年龄大小，只要是那些有抱负并乐于（也有能力）利用科技去挑战更多可能的人，都是创意精英。这些人的共同特点是：认真努力、乐于挑战现状、敢于从不同的角度切入问题。正因如此，他们才有如此强大的影响力。

在书的开头，我们会谈到如何吸引最顶尖的创意精英。我们首先从企业文化谈起，因为企业文化与企业的成败息息相关，如果连你自己都不信服自己的企业口号，那么你的企业又能走多远呢？此后，我们会谈及战略，因为最吸引创意精英的，莫过于那些有着强大战略基础的构想。创意精英明白，商业计划远远没有支持计划的支柱重要。之后，会谈到人才招聘，这是领导者最为重要的一项职责。延揽足够的俊材，让他们碰撞融合，必能激发出创意与成果。

随着企业的发展，沟通会变得越发重要（也越发困难）。

** 第一章 文化：相信自己的口号
杰夫在信中详尽地分析了问题出现的原因，提供了一份解决方案，并给出了五人利用周末时间编写出的解决方案模型及超链接，还附加了测试结果，证明新模型与当时通用的系统相比有哪些优越性。
如果他们失败了，没有人会以任何方式斥责他们；如果他们成功了，也没有人（包括广告团队的成员）会对他们的成绩起嫉妒之心。
对于多数企业而言，企业文化是自然发生的，不是人工植入的。这样的做法或许有效，但这意味着，你将成功至关重要的因素交给了命运。
创始人是企业文化的源头，而创始人为实现大计而物色并信赖的团队，才是企业文化的最佳体现。
注意不要通过海报或手册形式分享企业价值观，而要进行不厌其烦、推心置腹的交流。
如果你不能时常传达你的目标，不能通过奖励巩固你的目标，那么，你的愿景还不如打印愿景的纸有价值。
办公室的设计应本着激发活力、鼓励交流的理念，而不要一味制造阻隔、强调地位。方便的交流可以为创业精英们提供灵感，把创意精英聚集在一起，你就能引爆他们的思想。
混乱往往是自我表达和创新的衍生品，因此可以算是一种好事吧。
你不仅需要对你的团队抱有信任，也必须有足够的自信，这样，你才能给员工自由，让他们自己去寻找更好的答案。
我们把“提出质疑”作为一种硬性规定，而不是可做可不做。
而创意精英们却不然，他们之所以渴望扁平的企业结构，并不是因为他们想与上层平起平坐，而是因为他们希望多干实事，因此需要加深与决策者之间的沟通。
谷歌坚持按职能划分部门，将企业分为工程、产品、财务以及销售等部门，每个部门直接向首席执行官汇报。谷歌会把这种组织结构尽可能长地延续下去，因为我们认为，以业务或产品线为基础的组织结构会造成“各成一家”的局势，从而对人员和信息的自由流动形成扼制。
尽量不要把企业组织结构文件作为秘密隐藏起来。
组织应由小规模的团队构成。亚马逊创始人杰夫.贝佐斯曾对“两个比萨”原则推崇备至，这个原则规定，团队人数不能多到两个比萨还吃不饱。小团队要比大团队更有效率，他们不会花那么多时间勾心斗角。...在一家大规模的企业中，大小团队的存在都是必要的。
一条至关重要的组织原则是：找出最有影响力的人物，组织就以此人为中心。不要把岗位或经验作为选择管理者的标尺，而要看他的表现和热情。
你的头衔可以让你成为管理者，但让你成为领导者的，是你的员工。
那些无论你是否批准都按自己的想法做事的人，才值得你投资。
在管理层的顶端，最有影响力的人（也就是执掌企业运营大权的人）应该是产品的负责人。
在物色领导者的时候，要挑选那些不会将一己之利置于企业政体利益之上的人。
一旦找出了最有影响力的人，就应当赋予他们重任。把担子交到你最出色的员工手里时，你要相信他们会乐于承担，达到极限时他们会如实告诉你。
自高自大就是成功常见的一种副产品。
一家企业的品格是所有成员品格的总和，因此如果你想打造一家高品格的企业，就必须要求员工也有高品格。
作为管理者，一旦在团队中发现害群之马，最好的方法是减少其职责，并让骑士接手剩下的工作。对于极端败坏的恶行，你需要立即动手，把恶棍铲除出去。
恶棍一经发现，就需要及时处理；明星对企业的贡献足以支撑其狂妄，你就需要对他们多加容忍，甚至悉心保护。
工作与生活的平衡，是检验某种管理方式是否合理的试金石，但对于精明能干的员工而言，这个标准却缺乏合理性。其实这个标准本身就存在问题，因为对于很多人来说，工作是生活的一个重要组成部分，二者不可分割。
你只需要让员工知道他们需要对自己的工作负全责，这样，他们就会全力以赴地确保完成工作。给他们足够的空间和自由，让他们自己做主。
没有人对企业来说是不可或缺的。
添加流程或增设门槛的前提条件一定要严格，如果不是出于能够让人百般信服的业务上的考量，就不要增设这些障碍。
一家初创的伟大企业、一个炙手可热的项目或者一份好工作，都应该充满乐趣。如果你忙得焦头烂额，却没收获快乐，那就有问题了。
为一家初创企业奠定文化基础并不困难，而让一家已处在经营阶段的企业改变文化却难上加难。
有人说，一家公司就是某个领导人影子的延伸。
如果你决心开创一番新事业（或是对现有的事业做出彻底改造），就要面对冗长的工作日、无眠的夜晚，甚至连参加生日派对的时间都要被砍去。另外，你还必须聘请那些跟你志同道合、甘愿与你做出同样牺牲的人。要做到这一切，你必须拥有坚信自己定会成功的激情，也要拥有为梦想而实干的理性。这不仅需要你潜心投入、坚韧不拔，更重要的是要心无旁骛。在迎战敌军的时候，以色列坦克指挥官们并不会大喊“冲啊！”，而是会用“Ah'cha'rye”来动员自己的部队。这句话是希伯来语，翻译过来就是“跟我来”的意思。任何有志于做创意精英领导者的人，都需要拥有这样的态度。
通过这些行为，领导者们践行了平等理念：我们同舟共济，职责共担。但实际上，他们这么做，主要还是出于对公司的热爱。热情对领导力不可或缺，如果你缺少热情，就马上走人。
每家企业都应“不作恶”，这句话就如北极星一般，为管理方式、产品计划以及办公室政治指明了方向。

** 第二章 战略：你的计划是错误的
风险投资家应永远遵守投团队而不投计划的准则。
制订计划无可厚非，但是要明白，随着你对产品和市场了解的加深及事业的发展，计划也要随之所出调整。
计划可变，基础则岿然不动。
所谓的技术洞见，是指用创新方式应用科技或设计，以达到生产成本的显著降低或产品功能和可用性的大幅提升。
与满足消费者的现有需求相比，满足消费者尚未意识到的需求更为重要。
人们越来越重视西装革履，却忽视了实验室里穿的工作服。
最优秀的产品是靠技术因素而非商业因素赢得成功的，而在那些稍逊一筹的产品上，技术优势就不那么突出了。
找到一个具体问题的解决方案，然后想办法对这个解决方案加以拓展，这也是寻找技术洞见的一个方法。
以技术洞见来支撑产品研发，你就能够避免被消费者的需求牵着鼻子走，生产出步人后尘的产品了。
如果你有志做一番大事业，那么只靠增长是不够的，你还需要扩张，就是指在全球范围内快速发展某项事业。
选择了开放，你虽然放松了控制权，却换来了规模和创新。
如果你能像苹果一样通过封闭系统大获全胜，那么当然可以选择封闭。如果不能，那就选择开发吧。
如果你的工作只是击败那些和你套路基本相同的公司，那又谈何乐趣呢？
没有什么比竞争对手更能燃起我们的斗志了。
增长是重中之重。
确立一个大致的时间表，明确你希望达到的最终目标。
迭代必须快速，且必须以研究为基础。

** 第三章 人才：招聘是你最重要的工作
再多的战略也无法替代人才。

对于管理者而言，“工作中最重要的事情”是招聘人才。

在多数企业中，高管职位越高，对于招聘事宜越是不管不问。但实际上，这样的做法是本末倒置。

招聘目的应是尽可能吸引最优秀的人才，即便暂时没有与此人经验相匹配的空缺职位也应如此。

你只要招到几个优质人才，就会有一大群优质人才跟过来。

在企业急速发展带来的喧嚣中，人们往往难免在质量上妥协，而你的目标就是在招聘上严格把关，绝不妥协。

失败往往是不可避免的（正因为此，谷歌才如此看好擅长运动的人。因为运动能教人如何从失败中重新站起来，或至少提供了许多这种锻炼人的机会）。

不要太看重应聘者掌握了多少知识，而是要重视他们尚未开发的潜力。

坚持学习的人则永远年轻。人生中最大的乐事，莫过于保持头脑青春永驻。

在这种变动的背景下，雇用专家会留下隐患。本来被视为优势的专业知识和技能，会让专家在解决问题的过程中带有偏见，也会让他们难以接受由新洞见支持的创新解决方案。

寻找学习型动物颇具挑战。乔纳森常用的方法，是让应聘者对以前犯下的一个错误进行剖析。在刚刚步入新千年的时候，他会问应聘者：“1996年互联网发展浪潮中，你错失了哪些机遇？你做对了什么？做错了什么？”这是一个暗藏玄机的问题。这个问题先让应聘者说出自己的预见，又引导他们联系实际的观察和感悟，并逼他们承认自己所犯的错误。这是实实在在地承认自己的失误，而不是用“我最大的弱点就是我的完美主义”这样的话搪塞过去。对于这样的问题，谁也不可能给出虚假答案。

这个问题也可以用于近期发生的任何大事上。提这个问题的目的，不是检验对方是否有先见之明，而是看对方是如何从错误中总结经验、思想是如何走向成熟的。很少有人能给出令人满意的答案，但一旦出现让人眼前一亮的答案，你面前的应聘者很可能就是学习型动物了。当然，有的学习型动物会直截了当地告诉你：“我没有什么特殊禀赋，只是抱有狂热的好奇心。”这句话出自爱因斯坦之口。面对这样的人才，我们会毫不犹豫地招入谷歌（虽然他把“狂热”一词挂在嘴边，但创立相对论这个成就足以让我们忽视这一点小小的瑕疵）。

在把学习型动物招入公司之后，请让他们继续学习！为每位员工创造不断学习新东西的机会，即便是不能为公司带来直接利益的技能和经验也要让他们接触，然后，鼓励他们把所学的东西付诸实践。真正的学习型动物乐意利用各种培训和机遇来充实自己，因此，这样的要求对他们而言并不苛刻。但对于那些不喜欢尝试的人就要多加注意了：或许，他们并不是你认为的学习型动物。

通常，我们都会询问助理对应聘者的看法，也会听取他们的意见。

我们办事最有效率的一些同事，恰恰是我们最不想一起把酒言欢的人。和不喜欢的人共事不可避免，因为一家公司的全体员工不应该千篇一律，千篇一律恰恰是失败的温床。要想避免目光短浅，听到各不相同的观点是你最好的法宝。

你应该排除编程语言的限制，聘用你能找到的顶尖工程师，因为任它是Java、C、Python还是Go，最棒的工程师都能做到融会贯通。

雇用高层员工时，我们往往会以工作经验作为评判的基础。

要把招募人才纳入每位员工的职责，并进行评估。

首先要做些研究，对应聘者的身份和业绩加以了解。浏览应聘者的简历，看看这个人之前做过什么工作，然后用谷歌搜索引擎搜集有关应聘者及其业绩的相关信息。这么做，并不是为了搜出应聘者在狂欢节上的醉酒照，而是要对此人形成一个印象，看看他到底是不是个有趣的人。接下来，把搜集到的有关应聘者以往业绩的信息运用在面试过程中，加深你对此人的了解。必须要用富有挑战性的问题来调动应聘者的积极性：你上一次经手的项目遇到了什么样的阻力？（或为什么能够成功？）你需要识别出你对面的人到底是“鸡蛋”还是“石头”，是弄潮儿还是应声虫。

你的目标不是要进行一次礼貌的谈话，而是找到此人的局限，即便如此，面试过程也不应太过紧张。最理想的面试过程，就像友人之间的知性对话（比如“你现在在读哪些书？”）。你的问题应该深刻而广泛，问题的答案应是开放的（以此来试探出应聘者的思维模式），且要留出反驳的余地（这样，你就可以看看应聘者是如何捍卫和维护自己的观点的）。让不同的应聘者回答同样的问题不失为—种好方法，这样，你就可以对他们的答案有总体的把握了。

在问及应聘者的背景信息时，不要只让对方干巴巴地复述自己的经历，而是要让对方分享从经历中获得了什么样的领悟。鼓励对方展示自己的思想，而不是老拿简历说事儿。

要想了解对方的思想，“你经历过哪些出乎意料的事情？”这个问题不失为一个好的引子。因为这个问题与一般的面试问题有所不同，是应聘者始料未及的，这样，他们就不能用事先拟好的答案来应付，而必须稍微换个角度来审视自己的经历了。“你是怎么支付大学学费的？”“从你的网页历史记录里，我能得到哪些从你的简历上得不到的信息？”这些问题都能让你对应聘者有更深入的了解，因此都是好问題。除此之外，这些问题还非常具体，可以帮你判断对方对问题的倾听能力以及组织答案的能力。

面试中，情景问题往往很有帮助，这些问题尤其可以让你看到较为资深的应聘者给下属分派任务的方式以及是否信任下属，因此较适于向资历较深的应聘者提出。比如：“当你遭遇危机，或是需要做出一个重大决断的时候，你会怎么应对？”这样的问题，可以让你看出对方是那种“自己动手，丰衣足食”的类型，还是喜欢依靠他人帮助的类型。

前一种类型的人比较容易对下属产生不满，因此看重控制权；后一种类型的人则倾向于雇用优秀人才，也更信赖自己的员工。如果对方给出的答案过于空泛，说明此人对问题的认识所欠缺。应聘者给出的答案应该能引起你的兴趣，至少也应做到有的放矢。如果你得到的回答一听就是从营销报告中摘录下来的，或只是在泛泛地复述一些常识，那么你面前的而应聘者就是个一般人，不擅长深入地钻研问题。

每次面试都应该有一个结论，而不应该优柔寡断，模棱两可。

用人部门的经理虽然没有招聘决定权，却手握一票否决权。

谷歌的每份录用决定都需要经过他的审核（拉里）。

如果有人想在自己的团队中一手遮天，那么这样的人不用也罢。

有关升职的决策事关整个公司，如此重要的事宜，只交予少数管理者的话太欠考虑。相比之下，对晋升事宜使用委员会制度还有一个附带的好处：许多创意精英都不喜欢冲突，也磨不开面子回绝别人，而有了委员会制度，他们不必亲口对别人说“不”，只需要把这任务交给“铁面无私”的委员会。这些细节虽然微不足道，在他们为升职候选人评分时起到的安抚作用却出奇的好。

没错，高人就是要有高薪（如果他们的表现能达到预期水平的话），因为成功的运动员拥有特殊的技艺，能带来非凡的杠杆效应。...他们都能产生出超出常规的影响力。

只有在创意精英表现突出时，管理者才能给予优厚的回报。

在互联网时代，产品质量才是王道，因此，最高的报酬理应属于那些与卓越产品和伟大创意关系最密切的人。...在这里我们最为看重的，是人才带来的影响。

想要留住创意精英，最好的方法就是避免让他们太过安逸。...你还需要确保最有价值的员工的利益不受企业条条框框的制约。

请确保人员轮换的时候人是团队中的佼佼者。

这些人才的流失会造成巨大的连锁反应，因为这些人的下属或追随者往往也会和他们一起离开。

想要避免解雇不得力员工的窘境，最好的方法就是不要把他们招进来。

要在某个行业里脱颖而出，最简便有效的方法，是加深对行业的理解。

从事富有激情的事业堪称人生一大奢侈。

** 第四章 决策：共识的真正含义
而中国，无疑是个孕育顶尖工程师的地方。

要想达成有利于公司的决策，就需要有异议存在。

如果你是负责人，那么请注意，不要在回忆一开始就申明自己的立场。

最好的决策应该是正确的决策，而不是竭力争取大家一致同意而找出的最低标准，也未必是领导人自己的决策。

如果你不确定某种行为是否正确，那么最好的解决方法就是尝试，然后加以改进。

在决心行动之前，应该尽可能长时间地静观其变。

因而，决策者的职责就是准确地拿捏时机。把乐于行动的劲头拿出来，中止没有意义的讨论和分析，让团队行动起来，为实施决策而团结一心。

首先找出问题所在，然后进行商讨，最后设下解决问题的最后期限。

你大可以把决定权交予公司的其他领导者，只有他们出现严重的判断失误才需插手。

你的任务，就是分析数据、鼓励讨论、引导大家达成共识，凭借你过人的才识做出决策。

在面对重要决策时，运用领导力召集大家定期开会至关重要。如果决策足够重要，应该每天开会。

如果你想改变他人，不仅要晓之以理，更要学会动之以情。...否则，他们虽然能轻松做出聪明的决策，却往往无法很好地落实决策。

要从感情上承认一个自己并不同意的决策，人们必须首先感觉到自己的观点不仅得到了倾听，还得到了重视。

肯定了辩论败方，阐明了接下来的任务之后，决策者必须让相关人员要么保留异议、服从决定，要么就公开向上级汇报。

会议应该有一位决策者或主持。

与会者最好不超过8人，一般而言与会者越少，会议效果越好。

把80%的时间花在80%的收入上。必须把注意力和热情都集中在核心业务上。

正确的做法，是集中注意力寻找那些已经崭露头角、升职速度快的杰出创意精英。

** 第五章 沟通：当最牛的路由器
力量并不来自掌握的知识，而是来自分享的知识。这一点，应该在企业的价值观及奖励机制中体现出来。

我们却出人意料地将交给董事会的信息与所有谷歌员工分享。

董事会信息的共享还有一个附带的好处，那就是对质量的良性刺激。

作为领导者，你必须习惯于苦口婆心、诲人不倦。

如果你读到一篇见解深刻或生动有趣的文章，且文章的内容正好涉及你所传达的核心理念，那就和大家分享吧。

务必确保你愿意为自己工作，这是埃里克的一条最基本的原则，也是管理学的一条金科玉律。

电子邮件要迅速回复，可以很简短，例如我们就很喜欢用“明白了”这句话作答。

要做一个有思想的领导者，你就必须有自己的思想。

在接手新职位的前三周里，你不必做什么。你只需听取大家的心声，看看他们的问题和关注点在哪里、了解他们、关心他们、赢得他们的信任。

** 第六章 创新：缔造原始的混沌
如果你能召集一群顶尖的创意精英，再指派这世界上数一数二的创意精英负责管理，那么你所做的决策十有八九都是正确的。

有创意的人不需要别人来布置任务，而需要有人提供空间。

在发起一个行动时，吸引第一个追随者是至关重要的一步。

聚集用户，一切水到渠成。

谷歌收购摩托罗拉后发现，这家公司拥有几十款不同的机型，每款都以市场调查划分的特定群体为目标，这样的划分背后有其道理，毕竟不同的手机用户希望拥有自己独特的机型。但同时，这也会导致平庸。每款手机的专属产品研发人员虽然会努力造出伟大的产品，但他们也知道，只要产品还不错，就不会威胁到公司的生存。

相反，iPhone之所以能够获得如此之高的人气，正是因为这是苹果公司制造的唯一一款手机。如果新一代iPhone的研发遇到什么问题，想不出解决方案，团队中的任何人都不会回家。苹果公司的产品线精之又精，这并非巧合，因为每一款产品都“输不起”。

巨大的挑战往往是吸引以及留住创意精英的强大磁场。这样说吧，假定你是一个刚从大学毕业的优秀创意精英，在你面前摆着两份几乎完全相同的工作机会，唯一的区别在于，一家公司告诉你，他想要10倍的增长；而另一家公司仅仅满足于10%的进步。那么，你会如何选择？

追赶竞争者会让你以最快的速度陷入平庸。

将70%的资源配置给核心业务，20%分配给新兴产品，剩下的10%投在全新产品上。

资源上的稀缺，是激发创意的催化剂，没有什么比过度投资更能损害创意的发展。

谷歌的“20%时间”工作方式，允许工程师拿出20%的时间来研究自己喜欢的项目。

20%时间制最为宝贵的地方不在于由此诞生的新产品或新功能，而在于人们在做新的尝试时所学到的东西。绝大多数的20%时间项目都需要人们运用或磨炼日常工作之外的技能，也常需要他们与在工作上不常打交道的同事相互协作。即便这些项目很少能够演变为令人眼前一亮的新发明，却总能产生更多精干的创意精英。就像乌尔斯·霍泽尔常说的，20%时间制或许堪称一家企业最好的员工教育活动。

可以让用户习惯于先接受功能有所局限但质量过硬的新产品，然后再等着功能快速得到扩充的模式。

* 总结
谷歌是个极端注重工程师的公司。在谷歌，工程师并不是作为一个专业工种，而是一种类似“产品负责人”的身份存在的。他们有着商业头脑、专业知识、创造力以及实践经验，认证努力，乐于挑战现状、敢于从不同的角度切入问题。他们的用人思维是这样的：招最好的工程师，然后给他们足够的自由来发挥才智；当很多优秀的人才在一起时，他们互相之间会碰撞出创新的火花，以此来产生优秀的产品；竖立优秀的企业文化并不停践行（知行合一），以此引导所有人的行为。一旦找出了某个队伍最有影响力的人，就赋予他们重任。把担子交到最出色的员工手里时，相信他们会乐于承担。

因此，对于谷歌这套用人逻辑来说，最重要的事情就是招聘，也是我在这本书里找到的对于我们公司最能够借鉴的地方。上次勇哥问我面试的时候有什么技巧，我没答出来，现在正好借花献佛。我先总结一下谷歌的面试逻辑，再看我们如何应用到我们的工作里。

谷歌认为对于管理者而言，“工作中最重要的事情”是招聘人才。信息技术正在飞速发展，因而只是招聘技术专家是不够的，因为“被视为优势的专业知识和技能，会让专家在解决问题的过程中带有偏见，也会让他们难以接受由新洞见支持的创新解决方案”。因而他们需要招聘的理念是“不要太看重应聘者掌握了多少知识，而是要重视他们尚未开发的潜力”，即招聘“学习型人才”。

** 寻找学习型动物
那么如何寻找呢？“寻找学习型动物颇具挑战。乔纳森常用的方法，是让应聘者对以前犯下的一个错误进行剖析。在刚刚步入新千年的时候，他会问应聘者：“1996年互联网发展浪潮中，你错失了哪些机遇？你做对了什么？做错了什么？”这是一个暗藏玄机的问题。这个问题先让应聘者说出自己的预见，又引导他们联系实际的观察和感悟，并逼他们承认自己所犯的错误。这是实实在在地承认自己的失误，而不是用“我最大的弱点就是我的完美主义”这样的话搪塞过去。对于这样的问题，谁也不可能给出虚假答案。

这个问题也可以用于近期发生的任何大事上。提这个问题的目的，不是检验对方是否有先见之明，而是看对方是如何从错误中总结经验、思想是如何走向成熟的。很少有人能给出令人满意的答案，但一旦出现让人眼前一亮的答案，你面前的应聘者很可能就是学习型动物了。当然，有的学习型动物会直截了当地告诉你：“我没有什么特殊禀赋，只是抱有狂热的好奇心。”这句话出自爱因斯坦之口。面对这样的人才，我们会毫不犹豫地招入谷歌（虽然他把“狂热”一词挂在嘴边，但创立相对论这个成就足以让我们忽视这一点小小的瑕疵）。

这个问题也可以用于近期发生的任何大事上。提这个问题的目的，不是检验对方是否有先见之明，而是看对方是如何从错误中总结经验、思想是如何走向成熟的。很少有人能给出令人满意的答案，但一旦出现让人眼前一亮的答案，你面前的应聘者很可能就是学习型动物了。当然，有的学习型动物会直截了当地告诉你：“我没有什么特殊禀赋，只是抱有狂热的好奇心。”这句话出自爱因斯坦之口。面对这样的人才，我们会毫不犹豫地招入谷歌（虽然他把“狂热”一词挂在嘴边，但创立相对论这个成就足以让我们忽视这一点小小的瑕疵）。
”



在企业急速发展带来的喧嚣中，人们往往难免在质量上妥协，而你的目标就是在招聘上严格把关，绝不妥协。




通常，我们都会询问助理对应聘者的看法，也会听取他们的意见。

