#+TITLE: 伟大也要有人懂 读后总结
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2018-01-16 13:24>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

我的皮肤不够厚，不能把背朝向苦难的人间。

#+END_COMMENT

* 写在前面
这是一本韩毓海老师针对青少年讲马克思的书。

* 笔记
** 引子
个人怎样表现自己的生命，他们自己就是怎样。

唯物论的出发点就是现实中活动着的人、工作着的人、劳动着的人，就是那些“做事”的人、斗争着的人－－就是那些在凄风苦雨中反复跌倒又反复爬起来的“最被污蔑和诽谤的人”。

鲁迅这样说过：“战士战死了的时候，苍蝇们首先发现的是他的缺点和伤痕，嘬着，营营地叫着，以为得意，以为比死了的战士更英雄。但战士已经战死了，不再来挥去他们；于是乎苍蝇们即更营营地叫，自以为倒是不朽的声音，因为它们的完全，远在战士之上。
的确的，谁也没有发现过苍蝇们的缺点和创伤。
然而，有缺点的战士终究是战士，完美的苍蝇也终究不过是苍蝇。
去吧！苍蝇们！虽然生着翅子，还能营营，总不会超过战士的。你们这些虫豸们！”

知者行之始，行者知之成，圣贤只一个功夫，知行不可分为两事。没有经过“做事”历练的人，没有用自己的脚掌证实心脏的人，没有把动脑与动手结合在一起的人，便不可能是一个真正有知识的人，甚至不可能是一个活着的、现实的人。这样的人，一般而言，对于世界也就不可能采取唯物主义的立场与态度。
** 马克思究竟是哪里人？
马基雅维利在《君主论》里这样指出：被放债者所绑架，这就是罗马帝国崩溃的原因。...罗马公民道德的崩溃、法律的崩溃，其根源就在于“城邦内部的巨大不平等”。
滑铁卢战役的重大历史意义在于：它是历史上第一场资本家支配的战争，开辟了资本与军事强权联合统治的模式。它改变了人类历史，从此之后，一切人类战争往往只会有一个赢家，即投资于战争的资本家集团。国家已经沦为了“管理整个资产阶级共同事物的委员会”。
马克思于1818年生于罗马古都特里尔，他的父亲上溯五代都是拉比，而母亲这一脉则不知道有多少代。1794年，拿破仑军队开进莱茵河流域，实行了民主改革，当地备受岐视的犹太人的社会地位得到了较全面的改善。1815年，滑铁卢战役失利，莱茵地区归为普鲁士，犹太人又重新遭到不平等对待。马克思的父亲是法国人，因此最起码在思想归属上也属于法国人。
** 公民与市民的区别是什么？
卢梭在《爱弥尔》中说，公民，就是把自己看作共同体的一部分，并且原意为共同体献身的人；而市民就是自私自利，除了自己什么都不知道的人，就是孤立的人。
如果我们选择了最能为人类福利而劳动的职业，那么，重担就不能把我们压倒，因为这是为大家而献身；那时我们所感到的就不是可怜的、有限的、自私的乐趣，我们的幸福将属于千百万人，我们的事业将默默地、但是永恒发挥作用地存在下去，而面对我们的骨灰，高尚的人们将洒下热泪。

1843年秋，25岁的马克思在《论犹太人问题》这篇文章中，考察了西方社会私有化的历史。如果把希腊、罗马作为西方文明的源头，那么，罗马城邦共和体究竟是怎样衰亡的呢？马克思发现：罗马共和制的瓦解、公民道德的崩溃，正预示着基督教和犹太教的胜利，这一胜利开创了将“公共财富私有化”的历史先河。罗马的公共财产先是变成了教会的财产，然后，教会的财产变成了私人的财产。“私法是与私有制同时从自然形成的共同体的解体过程中发展起来的。”“共和的罗马”被封建的、基督教的“中世纪”所代替，教士和犹太人成了教会和王侯之间收租放债的中间人。最初的市民、资产阶级就是从“中间人”中产生出来的。拉丁语“Interesse”中介最终演化为了“Interest”利息一词。
随着教会获得统治地位，人们的交往方式发生了巨变。在罗马，交往就是人与人之间的交往，而在基督教社会，交往则是孤独的个人与上帝之间的交往，教会和教士则扮演着交往中介人的角色。由于基督教教义中名义上禁止利息，于是放债（后来称之为高大上的“金融业”）就落到了犹太人头上。马克思从犹太人身上找到了“市民”的原形。他说：犹太精神的世俗基础就是自私自利，犹太人的世俗礼拜就是经商牟利，就是通过交往和交换牟利，犹太人世俗的精神就是金钱－－因此，所谓“犹太精神”，也就是“市民社会的精神”。

在《论犹太人问题》中，马克思说：实际上文艺复兴并没有发现人，因为它只是发现了“商人”；法国大革命并没有解放人，因为它只是把“公民”变成了冷酷自利的市民；拿破仑的法令也没有把犹太人变成“公民”，而是要把所有人都变成“认钱为神”的犹太人。托尔斯泰在《战争与和平》中对拿破仑讽刺：拿破仑是个伟大的商人，他把政治道德变成了“政治算术”。

通过资产阶级革命，社会上的身份制度固然消失了，特权阶层的合法性在名义上似乎也被取消了，但是，这之后出现的，与其说是一个“平等”的社会，还不如说是弱肉强食的竞争社会。在这样的“市民社会”里，是否拥有权力、财富、地位，这全是你自己的“个人能力”的原因了－－也就是说，由于大家在“追求自我利益”、实现个人欲望方面是自由平等的，所以，你在竞争中失败，被人压迫侮辱，忍饥挨饿，流离失所，这一切都是你自己的责任，根本怨不得别人。在这样的社会里，人与其说是“独立”的，还不如说是互相对立、孤立无援的。由于人们之间的交往被等于了货币交换，于是，赢得更多的货币，就可以掌握交往、交换的主动权。赚钱本来是服务于幸福生活的手段，但现在它却成为目的，并与人的生活和生命完全对立起来了。青年马克思把这种荒谬、这种颠倒，称之为“异化”。
在这样的社会里，财富只属于掌握货币交换技巧的人，“有能力赢得货币”的人，于是，这样的社会里就没有、也不能容忍“公共财富”的存在；这个社会里的每个人，都只与货币发生关系，而与他人不发生直接关系，于是，他们只关心自己的、个人的、特殊的利益，从而把共同利益看作是完全外在于自己、并与自己对立的压迫性力量。由于个人与社会、特殊利益与共同利益处于完全对立的状态，因此，这样的社会，便是反对“共同利益”、反对“公民”的社会。
知识不过是从人们的共同劳动中总结出来的，如今知识却成为了知识者的特权，而劳动成为了劳动者的宿命。最早指出这种弊端的是卢梭，在《论科学与艺术的复兴是否有助于使风俗日趋淳朴》里这样说：我们有许多物理学家、几何学家、化学家、天文学家、音乐家、画家和诗人，但就是没有公民。如果还有的话，他们也是分散在穷乡僻壤，一生贫困，被人轻视。那些向我们提供粮食并向我们的孩子提供牛奶的人的处境，就是如此；我们对他们的感情，就是如此。
马克思青年时代所追求的“人的解放”，就是从目标和手段颠倒与异化中解放出来，就是从“市民社会”里解放出来，而“犹太人的社会解放就是从犹太精神中解放出来”。
在马克思看来，罗马帝国的腐败，就肇始于那些献身于“公共事业”的人被冷落鄙视，而现代社会腐败的根源，就是因为那些从事物质生活的劳动者，被“文明社会”所侮辱欺凌。
实际上，资产阶级所谓的“法律面前人人平等”，与基督教的“上帝面前人人平等”并没有根本的差别，因为它以法律上、政治上、“上帝面前”的人人平等，掩盖了现实社会的经济不平等。马克思青年时代就指出：市民社会绝不是人们所说的自由平等的牧歌乐园，恰恰相反，市民社会里有等级、阶级差别，有花园别墅和贫民窟，有血和泪，有剑与火。
** 我们应该怎样追求知识？
马克思从来不是直接提出自己的观点，而是尽可能占有已有研究成果和吸收他人观点的基础上，把自己的观点融入到对这些成果和观点的分析和批判之上。
在每一个所谓“事实”背后，都有描述者的意图，都有陈述事实的人给予世界的判断。那个判断总是说，“这个事实很重要，其他被忽略的东西不重要，因为它并不构成事实，或不代表事物的‘本质’。”但马克思说，那些为教科书所忽略的事实恰恰非常重要，这其中就包括占人类大多数、但却总是被忽视的普通劳动者，以及他们在历史中的作用。
“革命”，就是始终保持“运动”的状态。
共产主义对我们来说不是应当确立的状况，不是现实应当与之适应的理想。我们所称为共产主义的是那种消灭现存状况的现实的运动。
因为任何一个人的愿望都会受到任何另一个人的妨碍，而最终出现的结果就是谁都没有希望过的事物。
《资本论－－政治经济学批判》是“批判之作”的典范，而《共产党宣言》则是“革命的圣经”。
毛泽东极为天才地指出：“批判”和“革命”，这就是“处理两类不同性质的矛盾”的方法。“批判”的方法，针对的是人民内部的矛盾；而革命和斗争的方法，针对的则是“敌我矛盾”。
** 蜜蜂的活动和人的劳动有什么不同？
每个人所面对的，只能是他自己提出的问题。
“文明人毫无怨言地戴着他的枷锁”，而当人对于“文明”本身没有反思、没有批判的时候，他便不会感到自己是戴着枷锁的。
最蹩脚的建筑师从一开始就比最灵巧的蜜蜂高明的地方，是他在用蜂蜡建筑蜂房以前，已经在自己的头脑中把它建成了。劳动过程结束时得到的结果，在这个过程开始时就已经在劳动者的表象中存在着，即已经观念地存在着。他不仅使自然物发生形式变化，同时他还在自然物中实现自己的目的，这个目的是他所知道的，是作为规律决定着他的活动的方式和方法的，他必须使他的意志服从这个目的。
依据法律、遵守法律，这是创造文明的动力，是文明进步的基本条件。但非常不幸，法则、规范和规矩，同时也是对人的约束和压制，用卢梭的说法，它也是人类的“枷锁”。
青少年为什么要有一个苦闷的青春期呢？因为从那时起，他要学会适应社会、遵从各种社会法则，这个走向“成熟”的过程，就类似于卢梭所说的由“野马”变成“家马”的过程。而只有经历岁月荏苒，待到韶华不在，回忆早已逝去的青春和童真，人们才会像尼采那样不禁怆然。
人们说劳动创造了文明，但马克思在柏林大学的老师黑格尔却说：劳动作为“实践教育”，它与其说是一种教育或驯化，与人对于动物的驯化几乎没有什么不同，它的目的与其说是在于解放人，还不如说是“在于限制人的活动，即一方面使其活动适应物质的性质，另一方面，而且是主要的，使其能适应别人的任性”。
而马克思则说，人类的劳动和蜜蜂的活动不同在于：一方面，人类的劳动是把人头脑中的法则加诸物质世界；另一方面，劳动也是把法则加诸人的自由意志。前者是使自然服从法则，后者则是使人（的自由意志）服从法则。
劳动创造了世界，但这个世界则反过来构成了对于劳动者的压迫。
由于技术的发展、机器的采用，生产力成百上千倍地提高了，这样一来，全世界的劳动者就应该比产业革命之前大大地减少劳动时间和劳动量了吧？可惜，事实却恰恰相反。随着机器的采用，劳动效率尽管极大地提高了，但工人却被抛入了苦海。
人们通过劳动改造自然，使自然的东西成为人的产品、成为“我的东西”，这就是马克思所谓“使自然服从人的法则”；但是，人是在一定的社会条件下劳动的，是按照一定的社会法则劳动的，于是，劳动产品和劳动成果就不可能直接归于劳动者，而是归于他们所处社会里的“强者”，归于那个时代的社会法则的制定者，这就是马克思所谓“人使自己的自由意志服从社会法则”。
劳动者感到的不是他们在创造世界，而是在以自己的血汗养肥那些骑在他们头上的“强者”，那些强者却反过来压迫他们。
简而言之，所谓文化和文明就是一定社会的行为规范，指一定社会中占支配地位的社会法则。只有人类才能创造文化和文明，只有人类才能习得文化和文明，这就是人区别于动物的地方。这些规范和规矩是人类发展进步的条件，但是这种规范和秩序所造成的社会等级、社会差别、社会分工和社会角色的固化，却分裂着人类共同体，而这些社会法则也造成对于人的压迫和束缚。
** 爱情的力量是怎样帮助马克思摆脱痛苦的？
这就是新婚燕尔的卡尔马克思博士，他的父母有万贯家产，岳父是贵族高官，他娶了一位美若天仙的男爵小姐为妻，而他的朋友也都是达官贵人，至于他自己，不但剥削睿智，还有一份报酬丰厚的工作，在他面前，灿烂的前程如平坦的大路一般展开。沿着这条平坦的大路，卡尔马克思博士，他本来应该称为“马克思部长”，“马克思行长”，最不济也会称为“马克思教授”。
毫无疑问，马克思出身于统治阶级，更严格地说，他出身于统治阶级的上层。
马克思喝燕妮，他们不是太理想了，而是太现实了。
马克思和燕妮，他们与尼采和荷尔德林一样，不肯与那种流行的现实做丝毫的妥协，而尼采和荷尔德林最终都发疯了，但马克思与燕妮，却是完全清醒地携手走过了一生。
** 法应该建立在“伦理”的基础上，还是“公民道德”的基础上？
25岁的马克思写下了《黑格尔法哲学批判》这部手稿，这是他度蜜月期间的作品。
值得一提的是，马克思一开始写作的目的，就是为了享受探寻真理的快乐，所以，他并没有发表这部手稿的打算。实际上，马克思一生总是反复强调，写作的目的“是为了解决使我苦恼的疑问”，“目的不是为了付印”，即是对于自己全部的经济学研究，特别是《资本论》，马克思也一向采用这样的态度。
法理学和法律学认为：法律的目的是为了维护个人的利益和权利，是为了防止坏人做坏事；而法哲学则认为：“法律的目的是促进公益，养成公德”。
法哲学瞩目于良法与善治，追求理想的制度模式，而法律学瞩目于刑名责罚，追求的是“最不坏的制度”。如果再通俗一点说，法理学和法律学针对的是“小人”，而法哲学针对的则是“君子”。
黑格尔说，德国的法应该建立在普鲁士民族伦理的基础上，但是，究竟什么是普鲁士的伦理呢？马克思指出，这种伦理无非就是基督教的伦理罢了。因此，要批判普鲁士的法律，就必须批判它的基础--基督教伦理。
马克思认为，普鲁士一向以“神圣罗马帝国”的继承人自居，但它却并不知道，神圣罗马帝国并不是罗马共和制的继承人，因为它只是基督教会的继承人，是罗马公共财产的盗窃者，是罗马公民道德的摧毁者，是个装扮成继承人的小偷。
可见，当黑格尔在《法哲学原理》中声称“法”必须建立在“伦理”的基础上时，他其实是说：法律只能建立在基督教伦理的基础上，建立在孤独、孤立的“个人”的基础上，而不能建立在罗马的公民道德的基础上。
但马克思可不是普鲁士的官方哲学家，他青年时代的理想国是罗马城邦、是共和的法兰西，因此，马克思指出：“良法”与“善治”只能建立在“公民道德”和“公共事业”的基础上，建立在人们的社会交往而非个人与上帝的交流的基础上，因此，我们必须在基督教和资产阶级市民社会之外，为法律找到新的基础和现实承载者。
** 为什么马克思自称是黑格尔的学生，又反过来批判黑格尔呢？
黑格尔是以一种普鲁士官方的腔调去叙述孟德斯鸠和卢梭的观点的，而马克思则完全是“倒过来”，他是用一双法国式的眼睛，去阅读德国古典哲学的。
《法哲学原理》中最有趣的部分，是关于“市民社会”的讨论。黑格尔说，普鲁士贵族代表道德和伦理的体系，普鲁士国家代表法律的体系，而市民社会则是“需要的体系”，是“满足欲望的体系”。市民社会里的人在追求欲望满足方面是平等的，所以，他们就处于彼此冲突和竞争的状态。因此，大学绝不是培养市民的地方，因为市民社会里的人只能看的自己鼻子尖前面五米远的地方，这是一些毫无“觉悟”的人，他们根本不知道自己需要什么。黑格尔高傲地嘲笑说：如果市民社会里的人就是“人民”，那么“人民就是不知道自己需要什么的那一部分人。知道别人需要什么，尤其知道自在自为的意志即理性需要什么，则是深刻认识和判断的结果，这恰巧不是人民的事情。”

费尔巴哈、亚当斯密等人的缺陷就在于：他们只是说“人们是互相需要的”，但他们没看到，资本家需要工人，是因为工人能够给他们带来利润，而无产阶级却绝不需要资本家的剥削。

阶级并不是“等级”，任何社会都有许多等级，而阶级则是那个能够把自己的利益说成是全社会的利益，并以此夺取和掌握政权的等级，一切时代的统治阶级都是从市民社会里成长起来的。

单纯的阶级斗争观点，往往会影响我们对错综复杂的社会利益关系做出具体的、真实的分析。因为在现实中，统治阶级中存在着严重的利益分歧，而被压迫者总是被自私和短见所束缚，他们很难形成一个政治上整齐划一的阶级。

马克思用市民社会的发展史，代替了黑格尔所谓“伦理”的发展史。

马克思把黑格尔关于主人和奴隶之间关系的辩证思考，转变为资本与劳动之间的辩证思考。

黑格尔说，主人需要奴隶，是因为他需要“物质”；而奴隶需要主人，是因为他需要“精神”。而马克思则说，正如在古代社会，“主人”因为掌握了“精神”（宗教、文字和法律）而支配奴隶那样，在现代资本主义条件下，资本家因为掌握了“资本”（头脑）而支配着“劳动”（躯干）。

但是，马克思也清醒地认识到，资本主义社会的基本特征，它的运行逻辑，恰恰就是黑格尔所描述的那个样子：是“精神的人”在支配着“现实的人”，运动就是“精神”的自我复制、自我创造和自我生成，只不过在那里，“精神”采用了“资本”的形式罢了，因而，“精神的运动”，也无非就是指资本的自我循环和自我积累，于是，它方才表现为“虚你经济”对于“实体经济”的支配，金融资本对于商业资本和工业资本的支配，表现为一小撮资本家对于世界的支配。

实际上，资本主义世界并没有走出黑格尔的咒符。黑格尔学说，正是对资本主义世界最抽象的表述。

理论只要能说服人，就能掌握群众；而理论只要彻底，就能说服人。所谓彻底，就是抓住事物的根本。但是，人的根本就是人本身。
** 什么是共产主义呢？
共产主义就是对异化劳动的反抗，也是对基督教所开启的那个私有化进程的逆转。

共产主义不仅仅是发展生产力，共产主义就是要消灭生产力高度发达条件下出现的“两极分化”，即少数人暴富、大多数人“完全没有财产”的异化状态。

共产主义是从私有财产的普遍性来看私有财产关系的，所以共产主义不过是私有财产关系的普遍化和完成。

异化就表现为为人完全无法控制自己的命运，为了赚钱、为了出名，人们疲于奔命、永无尽头，而在这个异化的世界里，人们最大的不幸竟然是“到死了钱竟然还没花完”。

全部经济活动皆为利润和市场所支配，以至于这种支配完全不顾人的死活。

卢梭和黑格尔都说， 把人们深深地结合在一起的力量应该是爱。
我们今天依然会对孩子说：劳动创造了文明，就是因为劳动起源于对他人的爱。
但实际上，我们身边的社会却变得越来越冷漠了，这就是因为：不知从何时起，人们由互相依赖变成了“互相交换”，而“彼此需要”则变成了“有效需求”和“无效需求”。

亚当斯密教诲我们说：在市场里，只有“有效需求者”和“有能力的消费者”才是唯一值得尊重的。市场绝不会爱没有消费能力的人，反过来说，没有消费能力的人在这样的社会里也找不到“爱”。由于人们打交道的唯一方式就是货币交换，于是，人劳动的能力、创造的能力，人的魅力，通通变成了人的购买力，从而，衡量一个人是否优秀的标准，就是他有没有钱、有没有购买力、能不能消费，而并不是他的劳动能力、思想能力、创造能力，更不是他的道德情操和爱心--马克思说，这与其说是人的“异化”，还不如说是人的堕落。

我们现在假定人就是人，而人与世界的关系是一种合乎人的本性的关系，那么，你就只能用爱来交换爱，只能用信任来交换信任，等等。如果你想得到艺术的感受，那你就必须是一个有艺术修养的人。如果你想要感化别人，你本身就必须是一个能实际上鼓舞和推动别人前进的人。你跟人和自然界的一切关系，都必须是你的现实的个人生活的、与你的意志的对象相符合的特定表现。如果你在恋爱，但没有引起对方的爱，也就是说，如果你的爱作为爱没有使对方产生相应的爱，如果你作为恋爱者通过你的生命表现没有使你成为被爱的人，那么你的爱就是无力的，就是不幸。

什么是共产主义呢？或许我们可以这样说：如果有一天，你对现代政治感到厌倦；如果有一天你问自己为何到哪里都找不到真正的爱情；如果有一天你问自己：为什么我们总是控制不住赚钱、出名、攀比和支配他人的欲望；如果你发现自己不过是赚钱的工具而已；如果你终有一天发生了“人生和我们的世界究竟有什么意义”的疑问--拿就去读读《1844年经济哲学手稿》吧，你会知道共产主义并不遥远，而马克思的书，本来就是为你而写的。
** 马克思和恩格斯是完全一致的吗？
