#+TITLE: 
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2019-12-29 12:50>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: 

#+BEGIN_COMMENT PREVIEW

#+END_COMMENT

* 原理
简而言之，你在模拟跑马拉松的最后26千米，而不是开始的26千米。

和骨骼肌一样，心肌也可以通过训练加强。

最大摄氧量指“能摄入的氧气的氧气的总量”，就是跑步时人体运输和利用氧气的最大能力。当一个人最大摄氧量是50毫升/千克/分钟时，意思就是“每分钟内每千克体重摄入氧气50毫克”。

最大摄氧量 ＝ 0.178 × (m/15-150) + 33.3
1. 在跑到上尽全力尽可能快地跑15分钟，能跑多远跑多远。
2. 假设你跑了4022米。
3. 用这个数字除以15,换算出每分钟多少米。在示例中，4022/15 ＝ 268米/分钟。
4. 在这个268米/分钟的速度里，前150米按33.3算。
5. 剩下的118米乘以0.178, 再加上刚才的33.3 。

在确定你的最大摄氧量基线之后，你还要在训练中多次重复这个测试，来检查你的进步程度。

如果你考察一群精英级马拉松运动员，会发现他们的最大摄氧量水平非常接近；而将第1名和第10名分开的，就是厌氧阈值。最大摄氧量能将国家级选手和业余选手区分开来，厌氧阈值则可以将冠军和其他竞争者区分开来。

作为一名马拉松跑步者，你应该专注于训练身体而使用脂肪作为主要的能量来源。

过度依赖糖原储备能量的坏处就是，你只有大概两个小时的能量可用。

知道自己的轻松跑是在训练这项阈值就好了，怎么舒服怎么来。轻松跑不用太尽力，跑得时间尽量长一些就能提高阈值。

随着从脂肪中获得能量的增加，肌肉中的糖原就会延后使用，为更快的配速节省下来。“撞墙期”就会由此推迟，如果幸运的话永远都不会“撞墙”。

跑步经济性就是指跑步者跑在某个配速下所消耗的氧气总量。同等情况下，需要的氧气越少越好。在某个特定配速下持续训练，你在这个配速下的跑步经济性就会提高。因为目标就是在比赛配速下提高跑步经济性，所以你必须花相当多的训练时间在比赛配速上。
* 计划
** 轻松跑
轻松跑有大量重要的益处，且你不需要受任何伤痛就能获得比实质训练多得多的超负荷训练量。

你拥有的慢肌越多，你就越能做好准备把脂肪转化为能量。

你燃脂（而不是消耗碳水化合物）的时间越长，“撞墙”的时间就越能延后，这是糖原耗尽的结果。当你在低强度下跑步的时候，你的供能大约70%来自脂肪，30%来自碳水化合物。随着配速的增加，碳水化合物消耗所占的比例也会增加。你轻松跑的日子可以看作催化剂，用来促进慢肌生长，因此会尽量多燃脂、少消耗碳水化合物。

你每天的轻松跑能让心脏有更多机会适应适度的工作量，这比有限量的极大强度的工作要好得多。

汉森马拉松训练法对轻松跑的定义是比目标马拉松配速每千米慢37-64秒。比如，如果你的配速是每千米5分钟，你的轻松跑配速就应该是每千米5-6分钟。

如果你还想进步，就必须通过增加另一个轻松跑的日子（周三），或者在轻松跑的日子增加跑量，而不是简单粗暴地跑得更狠。

** 长距离跑
最长训练日里的长距离跑只要26千米就够了。但是有个技巧哦，长距离跑应该模拟马拉松的后26千米，而不是头26千米。

2-3小时是长距离跑新陈代谢适应的最佳“窗口”。一旦超过这个时间，肌肉就开始分解。

当然你在决定长距离跑跑多远之前，必须首先决定配速是多少。我们一般会让跑步者以轻松到稳健的速度跑。这并不是大跑量轻松跑的第一天，要把它看作长距离训练。

** 速度练习
轻松跑的日子是典型的低压力，但是速度练习则要求你像对待比赛一样认真，自律会是你获得的众多好处中的一个。如果说你昨天晚上去城里花天酒地了一夜，第二天早晨也许还能完成轻松跑；不过要是你想完成速度练习，前一天晚上就必须好好大吃一顿、好好大睡一觉。不管你如何完美地执行了这些练习，你付出一尺，训练将会回报你一丈。你完成的所有速度练习就像在银行里存了钱一样，当你在马拉松面对最困难的时刻，它就成为你可以召唤的资源。

速度练习最大的受益之处就是肌肉。

速度练习产生收益，而力量练习则维持收益。

在最大摄氧量100%时的配速只能维持3-8分钟。如果你是个新人，3分钟就差不多了；如果你是名精英运动员，顶多也就8分钟而已。最大摄氧量100%的情况下进行速度练习，将会导致结构肌肉开始分解，从而强迫你的身体更大地依赖厌氧资源。

** 力量练习
力量训练的强度会降到最大摄氧量的60%-80%,即比速度训练慢一些。速度训练相对来说会更短一些（比如3组1600米），因此会有一些恢复。但是力量训练的总量是速度训练的翻倍（比如10千米较高强度的跑步），恢复时间也相对较短。另外，力量训练的配速会比马拉松的目标配速快每千米6秒。

记住，永远都要在训练前后加2.4-5千米的热身和冷身。

** 节奏跑练习
如果你在起点时感觉良好，出发时比你计划的配速快每千米18秒，那么不到半路你大概就得扔毛巾认输了。

如果你想取得优秀的马拉松成绩，你最好在整个比赛过程中都维持稳定的配速，而不是采用忽快忽慢的策略。节奏跑将教会你一个重要的技巧：控制。

最大的好处，就是通过重复给你机会来稳稳地确定你的比赛配速应该是多快。只要花够了时间，你的身体就能有办法记住那个配速是什么感觉，最终就会形成第二天性的本能。

* 总结
训练分为轻松跑、速度跑、力量跑、节奏跑。

轻松跑
