#+TITLE: 必然 读后总结
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2019-11-29 09:02>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

成功将青睐那些以最优化的方式与机器人以及机器一同工作的人。

#+END_COMMENT

* 摘抄
科技在本质上有所偏好，使得它朝往某种特定方向。在其他条件都相同的前提下，决定科技发展动态的物理原理和数学原理会青睐某些特定的行为。

睁大眼睛，以一种警醒的态度来拥抱新科技则要有效得多。

不断变化不仅仅意味着“事物会变得不一样”，它也意味着流程——变化之引擎——比产品更重要。在过去二百年里，我们最伟大的发明恰恰是科学流程其自身，而非某个特定的工具或玩意儿。

这种能够产生持续改变和改进的方法性的流程要比发明任何产品都强上百万倍，因为自这种流程发明以来，我们已经借助它生成了数以百万计的新产品。

产品将会变成服务和流程。

当我们对科技的利用贴近于科技所偏好的轨迹时，我们才会在管理复杂性、优化利益和减少科技带来的伤害方面更加得心应手。

** Becoming
世间万物都需要额外的能量和秩序来维持自身，无一例外。

生命的本质，似乎主要是维持。

我们的工具越复杂，就越需要（而不是越不需要）我们的照料。

如果你拒绝进行不断的小升级，那么积累起来的变化会最终变成一项巨大的更新，大到足以带来“创伤”级别的干扰。

今天的问题来自昨天的成功。而对今天问题的技术解决方案，又会给明天埋下隐患。

亚马逊的崛起令人咋舌，原因不是它变成了“万货商店”（这点不难想象），而是因为亚马逊的顾客（其中就包括你和我）争先写下的评论。

几年前的一项研究发现，只有40%的网络内容是以商业形式创造出来的。

严格来说，今天的网络从技术角度上可以被定义成我们通过搜索引擎搜索到的一切。

** Cognifying
在所有谷歌搜索网站的狂热用户中，我不是唯一一个认为它撑不了多久的人。然而佩奇的回答让我一直难忘：“哦，我们其实在做人工智能。”

谷歌正利用搜索改善它的人工智能，而不是用人工智能强化它的搜索能力。

吴恩达这样解释道：“建设人工智能就像造一艘火箭飞船，需要一个巨大的引擎和许多燃料。飞船的引擎是各种学习型算法，而燃料是我们提供给这些算法的大量数据。”

网络规模扩大的速度远远赶不上其价值增加的速度。网络规模越大，对新用户的吸引力越强，这就让它（的规模）变得更大，从而更具吸引力，如此往复下去。

既然人工智能可以帮助人类成为更优秀的国际象棋选手，那么合理地推测，它也能帮助我们成为更优秀的飞行员、医生、法官、教师。

我们想要的不是智能，而是人工智慧。与一般的智能不同，智慧是专注的、能衡量的、专门化的。它还能够用完全不同于人类认知的方式思考。

众所周知，我们的思维方式不擅长做统计，所以我们制造出各种统计技术很强的智能设备，是为了让它们用不同的方式思考。

我们最重要的机械产品不是某样事情比人类做得更好，而是能做人类完全做不了的事情。

两百年前，70%的美国劳动力以农场为生。后来，自动化实现后，机器代替了农民以及在农场作业的动物，淘汰了大多数人的工作，只留下1%左右。但是被取代的农民并没有就此闲着。自动化转而在全新的领域中创造了亿万份工作。

如今，对手工中不完美的留恋，是我们购买手工纺织品的唯一理由。但是没有人想要一辆有瑕疵的汽车。谁也不愿意驾驶一辆性能不稳定的汽车以70英里时速在高速公路上飞驰。因此我们认定，在汽车的生产过程中人参与的程度越低越好。

任何时候你在点击搜索按钮时，都是在雇用一个机器人帮忙完成我们这个物种无法独立完成的事情。

自动化每一次微小的成功都会催生一些新职业，没有自动化的促进，我们不会想到这些职业。

成功将青睐那些以最优化的方式与机器人以及机器一同工作的人。

未来，你的薪水高低将取决于你能否和机器人默契配合。

** Flowing
美国对外出口的软件、音乐、电影和游戏价值连城，都是易于复制的产品。

新媒介最初的形态，是模仿它所取代的媒介。第一批商用计算机从办公室里借鉴了大量的比喻：我们的屏幕上有“桌面”和“文件夹”，还有“文件”；它们层级分明，秩序井然，和计算机将要颠覆掉的工业时代颇为相似。

信息混杂的上万亿条信息流汇聚一起，相互流动，便是我们口中的“云端”。

向实时的转变，以及复制品组成的云端破坏掉的第一个产业，是音乐产业。

经济学中有一条颠扑不灭的定理：一旦某样事物变得免费，变得无所不在，那么它的经济地位就会突然反转。

既然我们更喜欢和信任的人打交道，我们就会更经常地为信任支付额外费用。对此，我们成为品牌营销。有品牌的公司可以比没有品牌的公司在同类产品和服务中标出更高的价格，因为他们的承诺更容易被信任。

即时性是一种带着相对意味的概念（比如分钟之于小时），但它存在于所有的产品和服务中。

音乐深入到了我们生活的方方面面，试图占领我们全部的清醒时间。

** Screening
链接和标签或许是过去50年里最重要的发明。

用户没有意识到，每一个普普通通的点击，都是对一个链接的“投票”，这会提升它的相关等级。

维基百科之所以能够运行得这样不错，是因为它只需要一次点击就可以移除错误。

** Accessing
对事物的占有不再像曾经那样重要，而对事物的使用则比以往更加重要。

当亚马逊公司的创始人杰夫·贝索斯（Jeff Bezos）在2007年第一次介绍Kindle电子书阅读器时，声称Kindle并不是一件产品，而是使用阅读材料的一种服务方式。

今天，软件即服务（software as service，SAS）而非产品的理念，已经变成几乎所有软件的默认模式。

流动是难以拥有的，所有权似乎正从你指缝间流失。

网络的好处在于，它服务于我就像我拥有它一样，而我只需做很少的事情来维护它。

生态系统是一个相当恰当的比喻，因为平台就像一个雨林，一个物种（产品）的成功是建立在其他共存物种的基础之上的。

苹果公司设定规则和协议，并且监管经济往来。你可以说苹果公司的新产品就是这个市场自身。

在今天，最富有的以及最具破坏性的组织机构几乎都是多边平台，比如苹果、微软、谷歌、脸谱等公司。

由于云端的核心是动态分布的，所以一个云端要比一台传统的超级电脑更为强大。

根本上讲，将东西放置在云端上的首要目的是深度共享数据。相比于独自发挥作用，交织在一起的比特会变得更聪明也更强大。

云端的一个核心优势在于，它变得越大，我们的设备就变得越小巧、越轻薄。

如果麦克卢汉关于工具是我们自身的延伸这个观点是正确的——比如车轮是腿的延伸，相机是眼睛的延伸，那么云端就是我们灵魂的延伸。也或者你更加喜欢这种说法——它是我们的自我（self）的延伸。从某种意义上讲，它并不是我们拥有的自我的延伸，而是我们所使用的自我的延伸。

我们不断地连接云端，是因为它们比我们自身更可靠，并且它们确实比其他设备更让人信赖。

** Sharing
当一场席卷全球的浪潮将每个个体无时无刻地连接起来时，一种社会主义的改良技术版正在悄然兴起。

事实上，所有类型的维基都是集体主义的体现。

人们被鼓励自由和免费地复制这些产品的设计，并在此基础上开发新的产品。尽管没有金钱回报，但创造这些产品的大众生产者获得了信誉、地位、声望、享受、满足和体验。

共享技术其未曾言明但又不言而喻的目标是同时最大化个体自主性和群体协同力量。

等级架构向网络结构转变，中心化的领导机制向去中心化的网络机制转变，这是过去30年的主要文化进程，而这一过程还并没有停止。

在每个成功的无政府体系中总会存在一个长老会组织。

再微弱的等级制度也会让某些人受益，而让另一些人受损。

** Filtering
然而，只接触那些你已经喜欢的东西是有风险的，即你可能会卷入一个以自我为中心的漩涡，从而对任何与你的标准存在细微差异的事情都视而不见，即使你原本会喜欢它。

这种过适的状况会使他们的思维变得僵化。

从人类视角看，一个过滤器关注的是内容。但如果反过来，从内容的视角看，一个过滤器关注的是人类的注意力。

在信息丰富的世界里，唯一稀缺的资源就是人类的注意力。

既然它是最后的稀缺资源，那么注意力流向哪里，金钱就跟到哪里。

随着时间的发展，如果一个技术持续研发应用得足够久，它的费用就会开始向零靠近（但绝不会达到）。

几乎是我们在每个行业制造的每件东西，都在沿着同一个经济发展方向前进，那就是每天都变得更加便宜。

当所有商品的费用都在向零靠近时，唯一一件还在增加费用支出的事情就是人类的体验——这是无法被复制的。除体验以外的每样东西都在逐渐变得商品化，逐渐变得可以过滤掉。

** Remixing
所有的新技术都源自已有技术的组合。现代技术是早期原始技术经过重新安排和混合而成的合成品。

就大部分情况而言，我们的法律系统还停留在农耕时代的准则上，即将财产视为实体。

** Interacting
即使是我们能想到的最死气沉沉的设备，一旦为它们加上感官功能，使得它们变得可以互动，就会获得巨大改善。

我们可能会在这个设备上花几个小时，因此它的制作工艺至关重要。人们偏爱交互式的产品，而苹果是第一家意识到这一点的公司。

一个设备绸缎般光泽的表面触感，画面闪烁时的流畅性，温暖或冰冷的机身，制造工艺的质量，闪烁灯光的温度，这些东西对我们来说意义重大。

我们会继续给自己制造的事物添加新的传感器和感官功能。

互动发生的区域将会继续向我们靠近。

最大程度的互动会要求我们欣然融入到技术本身。

** Tracking
更微缩的芯片、更强劲的电池以及云端连接激励了一些自我追踪者尝试时间跨度很长的追踪，尤其在健康方面。

企业整合数据的行为几乎不受法律制约，因此许多公司成了政府的数据收集代理方。

尽管追踪和存储量呈爆炸性增长，日常生活的主要内容并没有被数字化。

今天我们被追踪时会感到不适，是因为我们不清楚谁在监督我们，以及他们知道多少信息。

从演化角度来说，互相监督是我们的本性状态。我认为，与诸多现代怀疑态度相反，人与人之间形成循环监督的世界不会受到强烈抵制，因为我们曾经像这样生活了数百万年。如果能实现真正的平等和对称，我们会感到舒适。

然而，在我见过的任何系统中，当匿名变成常态时，系统必然失败。

不用负责任的状态最大程度上释放出人类的恶。

** Questioning
长期以来，人类都在发明新的社会组织形式——从法律、法庭、灌溉系统、学校、政府、图书馆直到文明本身这个规模最大的组织。这些社会工具让我们成为人类，使我们的行为从动物的视角看来是“不可能”的。比如，人类发明了书写记录和法律后，一种在我们的灵长类近亲中不可能实现的公正变得可能，这种公正在口头文化中同样不会出现。灌溉和农业系统中的合作与协调产生了原本更加“不可能”的诸如预测、事先准备这类行为，以及人类对未来的敏感。人类社会向生物圈展示了各种先前不可能实现的行为。

我们没有必要刻意创造某种全球意识，只需要让每个人都能随时与他人以及其他事物相联通，并能共同创造新事物。

最近，受到过去发现的帮助，我们发现宇宙中96%的物质和能量是看不见的。宇宙不是由我们上世纪发现的原子和热量构成，而是由被我们称为“暗物质”和“暗能量”的未知存在构成。“暗”是无知的一种委婉说法，因为我们确实不知道宇宙中大部分物质由什么组成。

科学作为一种手段，主要增长了我们的无知而不是我们的知识。

** Begining
“硬奇点”指的是未来将由超级智能的胜利所奠定。

* 总结
