#+TITLE: 用户体验要素 以用户为中心的产品设计 读后总结
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2019-12-02 08:53>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: Book

#+BEGIN_COMMENT PREVIEW

简而言之，如果你的用户得到一次不好的体验，他们将不再回来。

#+END_COMMENT

* 用户体验为什么如此重要
用户体验并不是指一件产品本身是如何工作的，而是指“产品如何与外界发生联系并发挥作用”，也就是人们如何“接触”和“使用”它。

有些负责创建产品的人可能根本不会想到“设计”这个词。对于他们来讲，创建一个产品的过程更像是在“开发”：逐步建立和完善的特性和功能，直到它们所组成的那个东西在市场上是可行的。

对于这种人而言，产品设计是由功能决定的－－或者就像某些设计师常说的：“外形服务于功能。”这种观点对于产品的内部运作（那些用户看不见的部分）是完全适用的。但是，对于产品直接面对用户的部分－－按钮、布局、文字，也包括外观，正确的产品形态绝对不是由“功能”决定的，而是应该由“用户自身的心理感受和行为”来决定的。

产品越复杂，确定如何向用户提供良好的使用体验就越困难。在使用产品的过程中，每一个新增的特性、功能或步骤，都增加了导致用户体验失败的机会。

当人们使用这些深奥的技术遇到困难时，有趣的事情发生了：他们总是责备自己。他们认为自己一定做错了什么，觉得自己很愚蠢。

用户所能依靠的只有自己的智慧和经验，只能独自面对这个网站。

简而言之，如果你的用户得到一次不好的体验，他们将不再回来。

"特性"和“功能”总是重要的，但是用户体验对于客户的忠诚度有着更大的影响。所有的尖端技术和品牌营销邮件都无法让客户访问第二次。一次良好的用户体验可以－－而且你不会有太多的“第二次机会”去纠正它。

任何在用户体验上所做的努力，都是为了提高效率。这基本上是以两种主要形式体现出来的：“帮助人们工作得更快”和“减少他们犯错的概率”。

以用户为中心的设计思想非常简单：在开发产品的每一个步骤中，都要把用户纳入考虑范围。

用户体验对你很重要，其中一个最大的理由是：它对你的用户很重要。

** 认识用户体验要素
用户体验的整个开发流程，都是为了确保用户在你的产品上的所有体验不会发生在你“明确的、有意识的意图”之外。

事物都有两个方面，在较高层面的决定有时会促成对较低层面决策的一次重新评估（甚至是第一次评估）。在每一个层面，我们都根据竞争对手所做的事情、业界最佳的实践成果来做决定，这是最简单不过的老常识。

如果在开始较高层面设计之前完全确定较低层面的话，几乎可以肯定的是，你已经把你的项目流程－－也许是你最终产品的成功－－扔进了一个危险的境地之中。

+ 战略层 strategy
  用户需求
  产品目标可以是商业目的，也可以是其他类型的目标。

+ 范围层 scope
  功能规格

+ 结构层 structure
  交互设计

+ 框架层 skeleton
  信息设计
  界面设计
  导航设计

+ 表现层 surface
  感知体验

内容 － 内容至上
技术 － 在大多数案例中，你所能提供给用户的体验状态主要是由技术来决定的。

* 战略层 － 产品目标和用户需求
成功的用户体验，其基础是一个被明确表达的“战略”。知道企业与用户双方对产品的期许和目标，有助于促进用户体验各方面战略的确立和制定。

我们要通过这个产品得到什么？
我们的用户要通过这个产品得到什么？

"产品目标"和“用户需求”就组成了战略层，也就成为了我们在设计用户体验过程中做出每一个决定的基础。

关键词是“明确”。

** 产品目标
每一个我们做出的决定，都应该建立在我们确切地了解了它的影响力的基础之上。明确的定义“成功的条件”－－而不是定义“通向成功的路径”－－才能保证我们不会在这个阶段跑得太快。

在用户与产品交互的同时，企业的品牌形象就不可避免地在用户的脑海中形成了。

而将品牌形象具体且明确地写进目标，将会提高呈现出积极的品牌形象的机会。

这就是成功标准－－一些可追踪的指标，在产品上线以后用来显示它是否满足了我们自己的目标和用户的需求。

** 用户需求
但事实上我们并不是为自己设计，而是为其他人设计，如果想要这些“其他人”喜欢并使用我们创建的东西，那么就必须要了解“他们是谁”以及“他们的需求是什么”。只有投入时间去研究这些需求，我们才能抛弃自己立场的局限，真正从用户的角度来重新审视网站。

要对这些用户需求寻根求底，必须要定义谁是我们的用户。

我们无法提供一种方案可以同时满足这两种用户的需求。此时，我们要么针对单一用户群设计而排除其他用户群，要么为执行相同任务的不同用户群提供不同的方式。

这些人物角色档案可以印出来并且张贴在办公室周围，这样当我们要做决定时，可以问自己：“那会对Janet有用吗？Frank会有什么反应呢？”

产品目标和用户需求经常被定义在一个正式的战略文档（strategy document）或愿景文档（vision document）中。

让文档间接明了并切中要点即可。

不让你的团队阅读战略文档是很糟糕的。战略文档并不是创建出来被藏到某个地方，或只与少数几个资深员工分享的－－如果这些努力想要得到回报的话，在项目进行期间，此文档就必须被频繁地使用。

但是战略也应该是可以演变和改进的。

* 范围层 － 功能规格和内容需求
这个项目最大的绊脚石没有一个人愿意去定义需求。

用文档来定义产品需求，这件事很麻烦，但是你必须要做。

当前难以满足的需求，可以成为启动下一个版本的基础，这样就能形成一个不断循环的开发过程。

在范围层，我们从讨论战略层面的抽象问题－－“我们为什么要开发这个产品？”－－转向面对一个新的问题：“我们要开发的是什么？”

范围层确定的是全部的功能需求或功能规格。

当你把所有的时间都投入到维持现有产品时，你经常会忘掉哪些真正的限制条件，而哪些是为了简化产品而曾经做过的选择。

让一个工程师、一个客服人员、一个营销人员坐到一间会议室中谈论同一个产品，对大家都有启发意义。

我们需要的不是文档有多厚或多详细，而是要足够清楚和准确。功能规格说明书不需要包含产品的每一个细节－－只需要包含设计或开发过程中有可能混淆的功能定义。

功能规格必须可验证。

最棘手的部分是排列出哪些功能应该包含到你现在的项目中去。

不管怎样，如果你发现自己正在反复审视战略目标，那么你极有可能是太早地进入了需求定义阶段。

* 结构层 － 交互设计和信息架构
人类在使用产品的时候，用户和机器这两者之间就会产生某种类似舞蹈的步伐。用户移动，系统响应；接着用户再移动，来回应系统的响应，这样舞蹈才能继续进行。

每一位舞者都会告诉你，成功的舞蹈是要求每一个参与者能够预测对方的移动。

内容元素是一个位置还是对象并不重要；重要的是网站能够将这些内容元素从头到尾一致地表现出来，而不是有时候将此元素当成位置，有时候又当成对象。

如果你的用户也常常在其他网站购物，那么你最好也继续使用这种传统方式。使用人们熟悉的概念模型，会使用户很快适应一个不熟悉的网站。

我们不必将概念模型明确地告诉我们的用户。事实上，这样做会让用户觉得很混淆，反而无法帮助他们。

更重要的是，不要将比喻从现实世界中一字不落地照搬过来。

一些最令人反感的行为，往往出现在软件试图善意地修正用户错误的时候。

一连串的“你确定吗？”这样的警告通常会导致用户忽略了真正重要的那个，同时也被视为骚扰而不是帮助。

你是否有一位专家来解决结构问题并不重要，重要的是这些问题能由某个人来负责。

* 框架层 － 界面设计、航设计和信息设计
让你的界面与用户早已养成的那些习惯保持一致很重要，但是更重要的是，界面要与它自身保持一致。

你应该抑制在产品四周建立其比喻的冲动。对你的产品特性来说，必须是很可爱很有趣的，但是它们几乎无法像你幻想的那样产生作用。事实上，它们根本起不了作用。

这种方式往往不能揭示其特性的本质，反而会使其更加混淆。

界面设计要做的全部事情就是选择正确的界面元素。

哪个功能要在哪个界面上完成，是我们在结构层的交互设计中已经决定的；而这些功能在界面上如何被用户认知到，则属于界面设计的范畴。

成功的界面设计是那些能让用户一眼就看到“最重要的东西”的界面设计。

设计复杂系统的界面所面临的最大挑战之一，是弄清楚用户不需要知道哪些东西，并减少它们的可发现性（或者完全把它们排除出去）。

经验丰富的程序员，总是平等地对待每一种可能性，不管它代表了1个用户还是1000个用户。

这种思路对于界面设计是行不通的。一个将极端情况呈现出来的界面，等于给大多数用户提供一个设计不良的界面，而让少数用户满意。

界面设计可以采用各种各样的技巧，使用户完成任务的过程变得容易。一个简单的技巧，就是在这个界面第一次呈现给用户的时候，仔细考虑每一个选项的默认值。

另一个更好的做法，是能自动记住某个用户最后一次选择状态的系统。

当你有两个独立的信息架构师和设计师的时候，绘制出成功的线框图的唯一办法就是“协作”。

线框图是整合在框架层的全部三个要素的方法：通过安排和选择界面元素来整合界面设计；通过识别和定义核心导航系统来整合导航设计；通过放置和排列信息组成部分的优先级来整合信息设计。把这三者放到一个文档中，线框图就可以确定一个建立在基本概念结构上的架构，同时指出了表现层的设计应该前进的方向。

* 表现层
在框架层，我们主要解决放置的事情。界面设计考虑可交互元素的布局，导航设计考虑在产品中引导用户移动的元素的安排，而信息设计考虑传达给用户的信息要素的排步。

评估一个产品视觉设计的简单方法之一，是提出这样的问题：你的视线首先落在什么地方？哪个设计要素在第一时间吸引了用户的注意力？它们是对于战略目标来讲很重要的部分吗？

另一种找出主要设计元素的方法是眯着眼睛或斜着去看这个页面，直到你不能认出任何细节－－或者走到房间的另一头从那个地方来看这个页面。

它是一种所有人类共有的、对于视觉刺激而产生的、一系列复杂的原始本能反应。

呈现一个在其他媒体上有的、与你的产品不统一的样式，影响的不仅仅是访问者的印象；它还影响了他们对整个企业的印象。

这就是负责执行风格指南的团队在企业中的级别往往比你所预料的要高的原因。

* 要素的应用
你不能简单地依赖你的用户来阐明自己的需求。不管创建什么样的用户体验，其最大的挑战是“比用户自己更准确地去理解他们的需求”。

设计师和开发者总是在他们工作进行到某个阶段时，才后悔没有提前关注战略、范围和结构。

在视觉设计上的问题（看上去很混乱或混淆的布局，不一致或不协调的色彩）会让用户很快离开，从而永远不会意识到你在导航或交互设计上做了很多聪明的选择。
