#+TITLE: 翻译：Lisp Style Tips for the Beginner - Heinrich Taube
#+AUTHOR: slegetank
#+EMAIL: slege_tank@163.com
#+DATE: <2016-09-25 12:19>
#+SETUPFILE: ~/.emacs.d/org-template/level-1.org
#+blogtype: emacs

#+BEGIN_COMMENT PREVIEW

迁移。翻译。

#+END_COMMENT

原文：[[http://people.ace.ed.ac.uk/staff/medward2/class/moz/cm/doc/contrib/lispstyle.html][Lisp Style Tips for the Beginner]] 

本篇文章是一篇非正式的摘要，旨在帮助新手写出高效、易读的Lisp代码。

* 赋值

** 避免使用eval。赋值是Lisp内置的流程，所以你几乎没有任何理由自己调用它。如果你使用了它，那么请停下来并且重新思考一下你的问题，因为你解决问题的方法一定是错的。

** 熟悉宏。它是Lisp的一个重要特性，但是一个实现的很差的宏可以引起很严重的错误，而且对新手来讲很难解决。在你理解Lisp的解释器工作之前避免使用宏。绝不要编写宏来使代码“更高效”。

* 函数

** 绝不要像在C或者Pascal程序里那样实现函数。通常来讲，尽可能保持每个函数短小。每个函数应该只完成一项任务。实现很多小函数而不是几个大函数将会使你的代码更清晰、更模块化、更易重用。

** 在你开始实现某个函数之前，请确认Lisp是否已经实现了它！Common Lisp提供了数百个函数，宏以及特殊类型。请在开始你的编程工作前阅读[[http://www.cs.cmu.edu/afs/cs.cmu.edu/project/ai-repository/ai/html/cltl/cltl2.html][Common Lisp: then Language (2nd Edition)]] 中的相关章节来熟悉他们。 

** 如果你的函数返回不只一个结果，使用values而不是返回一个列表。如果你的函数不返回结果（C中的void），使用(values)来返回空值。

** 不要向你的代码中添加声明，除非你是一个Lisp老手并且完全确定那些变量将会被如何使用。

** 避免编写大块的case或者con块。考虑其他的方式，例如数据驱动的代码或者使用哈希表。

* 符号和变量

** Lisp程序员倾向于使用小写字母。使用横杠来构成多词语的符号，例如multi-word-symbol。Lisp通常是冗长的，所以请习惯输入长长的符号名称！

** 全局变量使用*来标识，例如*standard-output*。

** 全局常量使用+来标识，例如+default-number+。

** 使用setf而不是setq。setf表示SET Field。setf是setq的一种更通用的形式，它能设定几乎所有你在Lisp中可以“指向”，或者引用的东西。这包括变量，数组位置，列表元素，哈希表入口，结构字段，以及对象。

* 列表

** 使用first，reset，second等等而不是使用car，cdr，cadr。

** 注意破坏性的列表操作。他们高效但是也是代码中隐蔽bug的来源。

** 记住length必须和指针一起来找到列表的末尾。如果你多次调用了某个对象的length，那么请使用变量而不是多次调用length。

** 记住append会拷贝它的参数。避免在循环中使用append来向列表中添加元素。在loop中使用collect语句，或者将元素push到列表里然后使用nreverse将列表重新排序。
最坏：
#+BEGIN_SRC lispstyle
(let ((result ()))
  (dolist (x list)
    (setf result (append result (list x))))
  result)
#+END_SRC
好一些：
#+BEGIN_SRC lispstyle
(let ((result ()))
  (dolist (x list)
    (push x result))
  (nreverse result))
#+END_SRC
最好：
#+BEGIN_SRC lispstyle
(loop for x in list collect x)
#+END_SRC

** 记住copy只拷贝列表最外层的元素。使用copy-tree来拷贝整个列表。

* 条件

** 如果你并不需要条件语句的值，并且没有else分句，那么使用when和unless。否则，如果条件语句简单则使用if，否则使用cond。对于cond要在其结尾添加t语句。

** Lisp程序员经常使用函数和and、or来实现简单的条件计算。例如：
#+BEGIN_SRC lispstyle
(and x (setf y t))
#+END_SRC
等价于
#+BEGIN_SRC lispstyle
(when x
  (setf y t))
#+END_SRC
而
#+BEGIN_SRC lispstyle
(or x (setf y t))
#+END_SRC
等价于
#+BEGIN_SRC lispstyle
(unless x
  (setf y t))
#+END_SRC

* 循环
避免使用do，这会使代码难以阅读。对于简单的循环，dotimes和dolist都不错。如果你需要保存，存储或者修改循环的结果，那么loop几乎可能是最简洁、最高效的结构。一些Lisp程序员因为它“不像lisp”而拒绝使用它。然而loop是一个好用并且非常强大的特性。在花费了十分钟使用do之后，大部分Lisp程序员都很高兴loop的存在！

* 注释
请写注释。对于整体功能以及有点复杂的代码进行注释（你会在2星期内忘掉你是如何实现他们的）。Lisp提供了两种不同的注释。分号标记单行注释。Lisp会忽略掉分号之后的整行。分号并不需要一定在行首。例如：
#+BEGIN_SRC lispstyle
; this is a comment
(abs x) ; need absolute value here!
#+END_SRC
习惯上，Lisp程序员会区分单个、两个、三个分号的注释。单分号表示后面的注释用来解释同一行内的语句。两个分号表示该注释用来描述程序在该点的状态，或者用来解释下面这部分代码。两分号的注释需要跟它注释的代码具有相同的缩进。三分号注释提供全局的解释，并且总是在最左侧开始。例如：
#+BEGIN_SRC lispstyle
;;;  the next 20 functions do various sorts of frobbing
(defun frob1 (num)
  ;; return double frob of num
  (let ((tmp (random num)))      ; breaks if 0, fix!
    (double-frob tmp num :with-good-luck t)))
#+END_SRC
在#|和|#之间的文本将被注释掉。Lisp将会忽略掉其中所有的文本。#||#通常用来注释掉文件或者函数中的大块的代码。例如：
#+BEGIN_SRC lispstyle
#|
;;; i think this function is obsolete.
(defun frob2 (list)
  (frob-aux (first list)))
|#
#+END_SRC
将会注释掉一个不再使用的函数定义。

* 格式和缩进
坏格式的Lisp代码是很难阅读的。一份易读的Lisp代码的最重要的前提条件是使用简单、统一风格的缩进。有些编辑器，例如Emacs或者Fred，他们理解Lisp语意并且会替你完成这项工作。其他的文本编辑器，例如NeXTStep的Edit.app，除了括号匹配之外则不理解Lisp。即使你使用的编辑器并不能帮助你执行Lisp的缩进，你也应该自己花时间来格式化你的代码。下面是一些非常简单的规则：

** 如果你的编辑器提供多种字体，你都需要将你的Lisp代码使用一种等宽的字体来显示，例如Courier。

** 避免编写出长度超过70个字符的行。不要假设你的读者会把窗口大小调整的和你一样，而一旦换行则很难进行阅读。

** defun、defmacro或者let语句的语句体应该向里缩进两个空格。下面的例子中，defun和let都缩进了两列。let的缩进是相对let的定义开始的：
#+BEGIN_SRC lispstyle
(defun foo (a b &aux c)
  (setf c (* a b))
  (let ((d 1)
        (e (if (zerop b) t nil)))
    (check-compatibility d c)
    (foo-aux a b c d e)))
#+END_SRC

** 如果函数的参数占用了超过一行，后面的参数要和第一个参数保持相同缩进。下面的例子可以清晰的展示出compute-closure一共有三个参数：
#+BEGIN_SRC lispstyle
(setf s (compute-closure this-function
                         (list other-function my-method)
                         56))
#+END_SRC

** 不要使用tab来缩进，并且不要在单独一行结束括号。C语言的风格在Lisp里看起来很傻。例如下面的代码：
#+BEGIN_SRC lispstyle
(defun my_Foo (x)
    (let ((y (* x 5))
         )
        (values y x)
    )
)
#+END_SRC
在Lisp程序员看来这样的格式更好：
#+BEGIN_SRC lispstyle
(defun my-foo (x)
  (let ((y (* x 5)))
    (values y x)))
#+END_SRC

